export const meta = {
  name: 'geography-queue-research',
  description: 'Research + author the geography bank v2 topic queue: one Opus researcher per sub-strand across five sections (city/nature/ancient/culture/earthsystem), Grokipedia-first, PLACE->WONDER, place-anchored lane. Returns richly-scoped topic ladders.',
  phases: [
    { title: 'Research', detail: 'one researcher per sub-strand -> rich place-anchored topic-ladder specs' },
  ],
}

// ---- the five sections, split into focused sub-strands with seed places (canon breadth). ----
// Each agent proposes ~n topic LADDERS for its sub-strand, adding/merging beyond the seeds as its
// research warrants. section+strand are injected on write (fixed per sub-strand), so the agent omits them.
// PLACE ladders (city/nature/ancient/culture): one PLACE deepened. THEME ladders (earthsystem): one
// earth-process deepened ACROSS the places that show it.
const SUBSTRANDS = [
  // ================= CITY -- one city deepened; architecture, hidden marvels, the culture born there =================
  { slug:'city_europe_west_south', section:'city', strand:'Cities of Europe -- west & south', n:12,
    seeds:'Paris (the Catacombs of ~6M bones; Sainte-Chapelle\'s glass; the Metro\'s Art Nouveau entrances; Pere Lachaise); London (the tower ravens; the Underground, world\'s first; the Great Fire of 1666); Rome (the Pantheon\'s open oculus; the Appian Way; the aqueducts); Florence (Brunelleschi\'s self-supporting dome); Venice (a city on millions of driftwood piles; acqua alta; Murano glass island); Naples (the city living under Vesuvius); Barcelona (Gaudi\'s still-unfinished Sagrada Familia); Granada (the Alhambra\'s water gardens); Lisbon (the 1755 earthquake that shook the Enlightenment); Amsterdam (a city of canals below sea level); Bruges (the belfry carillon)' },
  { slug:'city_europe_central_nordic', section:'city', strand:'Cities of central, northern & eastern Europe', n:12,
    seeds:'Vienna (the waltz born in its 1820s ballrooms; the coffee-house culture); Prague (the 600-year astronomical clock; Charles Bridge); Budapest (built over 100+ thermal springs); Krakow (the Wawel dragon\'s cave; the intact medieval old town); Reykjavik (a capital heated by geothermal water); Stockholm (a city across 14 islands; the raised Vasa warship); Bergen (the Hanseatic Bryggen wharf); Tallinn (the intact medieval walled town); Athens (the Acropolis crowning the city; the Agora where Socrates walked); Dubrovnik (the complete sea-walls); Moscow (Red Square; the palace-like Metro stations); St Petersburg (built on drained marsh by decree; the White Nights)' },
  { slug:'city_mideast_north_africa', section:'city', strand:'Cities of the Middle East & North Africa', n:12,
    seeds:'Petra (the rose-red city the Nabataeans carved into a gorge, hidden behind the Siq); Istanbul (the only city on two continents; Hagia Sophia; the Basilica Cistern beneath the streets); Jerusalem (the walled old city of four quarters); Cairo (the pyramids at the desert edge of a megacity; Islamic Cairo); Alexandria (the vanished Lighthouse and Library); Marrakech (the medina and the Jemaa el-Fna); Fes (Al-Qarawiyyin, arguably the oldest continuously running university); Isfahan (the vast Naqsh-e Jahan square; blue-tiled domes); Damascus (among the oldest continuously inhabited cities); Sanaa (the mud-brick "skyscrapers" of the old city); Baghdad (the House of Wisdom); the qibla-axis significance of Mecca as a place' },
  { slug:'city_central_south_asia', section:'city', strand:'Cities of Central & South Asia', n:11,
    seeds:'Samarkand (the Registan\'s three madrasas; the Silk Road hub); Bukhara (the Kalyan minaret Genghis Khan spared; the intact old city); Khiva (the walled desert town); Lahore (the Badshahi Mosque; the Shalimar Gardens); Delhi (the Red Fort; the rust-resistant iron Qutb pillar; Humayun\'s Tomb, the Taj\'s precursor); Agra (the Taj Mahal built in grief; Fatehpur Sikri, the abandoned city); Jaipur (the Pink City painted for a prince; the Jantar Mantar giant stone instruments); Varanasi (among the oldest living cities; the cremation ghats on the Ganges); Kathmandu (the Durbar squares; Swayambhunath); Lhasa (the Potala Palace towering on its hill)' },
  { slug:'city_east_asia', section:'city', strand:'Cities of East Asia', n:11,
    seeds:'Xi\'an (the buried Terracotta Army; the eastern end of the Silk Road; the intact city wall); Beijing (the Forbidden City, the largest palace complex; the Temple of Heaven; the hutong lanes); Shanghai (the colonial Bund facing the space-age Pudong skyline); Hong Kong (Victoria Peak; the densest skyline); Pingyao (a fully intact Ming-dynasty walled city); Seoul (Gyeongbokgung; the strangest border on Earth just north); Gyeongju (the Silla royal burial mounds); Tokyo (Shibuya crossing; the moated Imperial Palace); Kyoto (the golden Kinkaku-ji; the thousand vermilion torii of Fushimi Inari; the bamboo grove); Nara (the Great Buddha; the free-roaming deer); Hiroshima (the preserved Atomic Dome)' },
  { slug:'city_southeast_asia', section:'city', strand:'Cities of Southeast Asia', n:11,
    seeds:'Bangkok (the Grand Palace; the reclining Buddha of Wat Pho); Ayutthaya (the Buddha head cradled in strangler-fig roots); Bagan (the plain of thousands of temples); Yangon (the gold Shwedagon Pagoda); Angkor / Siem Reap (gateway to the temple-city -- note history overlap); Luang Prabang (the dawn alms-giving procession); Hanoi (the old quarter of 36 trade streets); Hue (the imperial citadel); Hoi An (the lantern-lit trading port); Singapore (a city-state that keeps growing on reclaimed land; Gardens by the Bay); Yogyakarta (gateway to Borobudur and Prambanan -- note ancient overlap); Bali (the cliff temple of Uluwatu); Manila (Intramuros, the walled Spanish quarter)' },
  { slug:'city_subsaharan_africa', section:'city', strand:'Cities & towns of Sub-Saharan Africa', n:10,
    seeds:'Lalibela (the eleven churches hewn DOWN into the rock, monolithic); Aksum (the towering carved stelae of the Ethiopian kingdom); Gondar (the Ethiopian castles); Harar (the walled Muslim old town; the hyena men); Great Zimbabwe (the vast dry-stone walls built without mortar); Timbuktu (the mud Djinguereber mosque; the ancient manuscript libraries); Djenne (the Great Mosque, the largest mud-brick building, re-plastered each year); Stone Town, Zanzibar (the Swahili-coast trading town; carved doors); Cape Town (Table Mountain; Robben Island); Goree Island / Dakar (the Atlantic slave-trade memory -- honest history); Lagos (the largest African metropolis)' },
  { slug:'city_north_central_america', section:'city', strand:'Cities of North & Central America', n:10,
    seeds:'New York (the Brooklyn Bridge; the planned rectangle of Central Park; Grand Central\'s backwards constellation ceiling); Chicago (birthplace of the skyscraper; the river engineers reversed); New Orleans (the French Quarter above the flood grade; jazz\'s birthplace as a PLACE); San Francisco (the Golden Gate\'s "international orange"; Alcatraz; the only intact cable-car system); Washington DC (L\'Enfant\'s planned diagonal avenues; the monument axis); Quebec City (the only walled city north of Mexico); Montreal (Mount Royal, Olmsted\'s park); Mexico City (built on a drained Aztec lake, and slowly sinking; the vast Zocalo); Havana (the Malecon sea-wall; old Havana); Cartagena (the walled Caribbean fortress-city)' },
  { slug:'city_south_america_oceania', section:'city', strand:'Cities of South America & Oceania', n:12,
    seeds:'Cusco (the Inca capital, the "navel" of the empire, laid out as a puma); Lima (the pre-Inca adobe huacas among the modern city); La Paz (the highest de-facto capital; the cable-car transit); Potosi (the silver mountain that funded an empire); Rio de Janeiro (Christ the Redeemer on Corcovado; Sugarloaf); Buenos Aires (the tango born in the La Boca docklands; the Recoleta cemetery city); Valparaiso (the hill funiculars); Ushuaia (the southernmost city); Sydney (the Opera House\'s sail-shells; the Harbour Bridge); Melbourne (the laneways); Auckland (a city built on ~50 volcanic cones); Wellington (the windiest capital); Rotorua (the geothermal Maori town of geysers and mud pools)' },

  // ================= NATURE -- one natural wonder deepened; the landscape & the earth-fact of THAT place =================
  { slug:'nature_waterfalls_rivers', section:'nature', strand:'Great waterfalls & rivers', n:11,
    seeds:'Iguazu Falls (275 cataracts on the Brazil-Argentina border; the Devil\'s Throat); Niagara (the Horseshoe Falls; its slow upstream retreat); Victoria Falls ("Mosi-oa-Tunya", the smoke that thunders; the Devil\'s Pool at the lip); Angel Falls (the tallest, off a Venezuelan tepui); the Nile (the world\'s longest, flowing NORTH; the White and Blue meeting at Khartoum); the Amazon (a fifth of Earth\'s river water; the pink river dolphins; the Meeting of the Waters that runs unmixed); the Yangtze (the Three Gorges); the Mekong; the Ganges; the Mississippi (its meanders and oxbows; the birds-foot delta); the Congo (the deepest river)' },
  { slug:'nature_lakes_inland_seas', section:'nature', strand:'Lakes & inland seas', n:10,
    seeds:'Lake Baikal (the oldest and deepest lake, a fifth of Earth\'s unfrozen fresh water; the only freshwater seal); Lake Titicaca (the highest navigable lake; the Uros reed islands); Lake Superior (the greatest freshwater surface); Lake Tanganyika (the second-deepest); the Dead Sea (the lowest exposed land, so salty you float, and shrinking); the Caspian (the largest inland body of water); the Aral Sea (drained to dust by Soviet cotton irrigation -- honest); Crater Lake (a caldera of impossibly blue water); Lake Natron (the red, petrifying soda lake); the pink lakes (Hillier; Retba) -- the algae/salt chemistry as a place-fact' },
  { slug:'nature_mountains_ranges', section:'nature', strand:'Mountains & ranges', n:11,
    seeds:'Everest (marine fossils on the summit from an ancient seabed; still rising ~4mm/yr; Hillary & Tenzing 1953); K2 (the "savage mountain"); Kilimanjaro (three volcanic cones rising from the savanna; the shrinking summit ice); Denali; the Matterhorn (the glacier-carved horn); Mount Fuji (the near-perfect cone); Mount Kailash (unclimbed, sacred to four faiths); the Andes (the longest continental range); the Himalayas (still rising from the India-Eurasia collision); the Karakoram; the Alps (Mont Blanc, first climbed 1786); the Appalachians (older than bones, older than Saturn\'s rings)' },
  { slug:'nature_deserts', section:'nature', strand:'Deserts', n:10,
    seeds:'the Sahara (the largest hot desert -- and green savanna with rivers just ~6,000 years ago); the Atacama (the driest place, where some weather stations have never recorded rain; the clear-sky observatories); the Namib (among the oldest deserts; the Skeleton Coast shipwrecks; where dunes meet the sea); the Gobi (the two-humped Bactrian camels; bitter winter cold); the Arabian Empty Quarter (Rub\' al Khali); the Kalahari; the Sonoran (the saguaro grows nowhere else); the Taklamakan (the desert of "no return"); the Lut Desert (the hottest surface temperature ever measured); the Australian Outback (the Red Centre); the "Door to Hell" gas crater at Darvaza' },
  { slug:'nature_polar_glacial', section:'nature', strand:'Polar & glacial wonders', n:9,
    seeds:'Antarctica (Earth\'s largest fresh-water store, locked as ice up to ~2 miles thick; no permanent residents; the ice-free Dry Valleys; Lake Vostok sealed beneath the ice); the Arctic Ocean (the smallest, shallowest; the North Pole sits on drifting sea ice, no land); the Greenland ice sheet; Vatnajokull (Europe\'s largest glacier; the blue ice caves); Perito Moreno (the calving glacier); Svalbard (the doomsday seed vault); permafrost and the methane it holds; how icebergs calve and drift (the Titanic\'s berg)' },
  { slug:'nature_oceans_reefs_coasts', section:'nature', strand:'Oceans, reefs & extraordinary coasts', n:10,
    seeds:'the Mariana Trench (Challenger Deep, the deepest point; the 1960 descent); the Pacific (larger than all land combined); the Great Barrier Reef (the largest living structure, visible from orbit); the Belize Barrier Reef and its Blue Hole; the Red Sea (widening as Africa and Arabia split); the Bay of Fundy (the highest tides on Earth, ~16 m); the Sargasso Sea (a sea with no shores, bounded by currents; where eels spawn); mangrove coasts as storm buffers; kelp forests; the Norwegian maelstrom whirlpools; the cenote-and-reef Yucatan coast' },
  { slug:'nature_geological_wonders', section:'nature', strand:'Geological wonders & strange landscapes', n:13,
    seeds:'the Grand Canyon (the Colorado cutting through ~2 billion years of rock); Bryce Canyon (the hoodoo spires); Cappadocia (the fairy chimneys and underground cities carved in soft tuff); Pamukkale (the white travertine "cotton castle" terraces); Salar de Uyuni (the largest salt flat, a mirror when wet); the Giant\'s Causeway (the hexagonal basalt columns; Fingal\'s Cave); Devil\'s Tower (the igneous intrusion); Uluru (the great sandstone inselberg glowing red); the Chocolate Hills of Bohol; Wave Rock; Mount Roraima (the flat-topped tepui "lost world"); Yellowstone (Old Faithful; the Grand Prismatic\'s thermophile colors); the Dallol acid pools; the Zhangye rainbow mountains' },

  // ================= ANCIENT -- one site deepened as PLACE-WONDER; FLAG same-fact overlap with the history bank =================
  { slug:'ancient_egypt_near_east', section:'ancient', strand:'Ancient Egypt & the Near East', n:11,
    seeds:'the Great Pyramid of Giza (aligned to the cardinal points; the last standing ancient wonder); the Sphinx; Karnak\'s forest of hypostyle columns; Abu Simbel (cut apart and lifted whole above the rising Aswan lake); Petra (the Nabataean water engineering that made a city bloom in a desert gorge); Palmyra (Zenobia\'s desert-caravan city); Baalbek (the Temple of Jupiter\'s megalith blocks); Persepolis (the Apadana stair of tribute-bearers); Babylon (the reconstructed Ishtar Gate); Gobekli Tepe (a monumental temple ~11,500 years old, older than farming and pottery); Catalhoyuk (the Neolithic proto-town with no streets, entered from the roof)' },
  { slug:'ancient_mediterranean_prehistoric_europe', section:'ancient', strand:'Ancient Mediterranean & prehistoric Europe', n:12,
    seeds:'Troy (Schliemann\'s nine cities stacked in one mound); Mycenae (the Lion Gate; the cyclopean walls); Knossos (the Minoan palace and the labyrinth myth); Delphi (the oracle at the "navel of the world"); Pompeii & Herculaneum (a city frozen by Vesuvius in AD 79; carbonized scrolls); the Colosseum (flooded for mock sea-battles); the Pantheon (the largest unreinforced concrete dome, still standing); Stonehenge (bluestones hauled from Wales; the solstice alignment); Newgrange (older than the pyramids; the midwinter sunbeam into the inner chamber); Carnac (thousands of standing stones); Lascaux/Chauvet (Ice-Age painted caves); Skara Brae (the Neolithic village revealed by a storm); Ggantija (Malta\'s temples, among the oldest free-standing buildings). NOTE: flag overlap with the history bank.' },
  { slug:'ancient_asia', section:'ancient', strand:'Ancient marvels of Asia', n:12,
    seeds:'Angkor Wat (the largest religious monument, its towers a stone model of the cosmos); Angkor Thom and the Bayon\'s serene stone faces; Ta Prohm (the temple in the grip of strangler-fig roots); Borobudur (the largest Buddhist monument, a stone mandala you climb); Prambanan; Bagan; Sigiriya (the palace-fortress on a lion rock); the Ellora Kailasa temple (carved DOWNWARD from a single rock); the Ajanta cave frescoes; the Taj Mahal (grief in white marble; note cross-listing); Mohenjo-daro & Harappa (the Indus cities with grid streets and covered drains, script still undeciphered); the Great Wall (its true length ~21,000 km); the Terracotta Army guarding the First Emperor. NOTE: flag overlap with the history bank.' },
  { slug:'ancient_americas', section:'ancient', strand:'Lost cities & marvels of the Americas', n:14,
    seeds:'Teotihuacan (the Avenue of the Dead; the Pyramid of the Sun -- built by a people whose name we don\'t even know); Palenque (Pakal\'s tomb deep in the Temple of the Inscriptions); Tikal (jungle pyramids above the canopy); Chichen Itza (the serpent-shadow that slithers down El Castillo at the equinox); Tulum (the cliff-top Maya port); Monte Alban (the Zapotec hilltop city); Tenochtitlan (the Aztec island capital beneath modern Mexico City); Cahokia (the largest pre-Columbian city north of Mexico; Monk\'s Mound); Mesa Verde (the cliff dwellings); Chaco Canyon (the astronomically aligned great houses); Caral (among the oldest cities in the Americas); the Nazca Lines (geoglyphs whose purpose is still debated); Machu Picchu (the cloud city Bingham reached in 1911); Sacsayhuaman (Inca stones fitted so tight no blade slips between); Easter Island (the moai, and the oral tradition and rocking-gait experiment for how they "walked")' },
  { slug:'ancient_africa_pacific', section:'ancient', strand:'Ancient Africa & the Pacific', n:10,
    seeds:'the Nubian pyramids of Meroe (steeper and MORE numerous than Egypt\'s); the Aksum obelisks (carved from single granite blocks); Lalibela\'s rock-hewn churches (cross-listed as a place); Kilwa Kisiwani (the Swahili-coast trade city); the Timbuktu manuscript tradition; Nan Madol (a city of ~100 artificial islets built on basalt logs in Micronesia); the Tongan Haʻamonga ʻa Maui trilithon; Polynesian wayfinding (reading stars, swells, and birds to settle a tenth of the planet); Lapita pottery marking the Pacific migration trail; Great Zimbabwe (cross-listed). NOTE: flag overlap with the history bank.' },

  // ================= CULTURE -- a cultural creation BORN in a place (NON-FOOD; food origins belong to COOKING) =================
  { slug:'culture_music_dance', section:'culture', strand:'Music & dance born in a place', n:13,
    seeds:'the Waltz (1820s Vienna -- scandalous for the closed embrace); the Tango (the Buenos Aires/Montevideo docklands); Jazz (New Orleans) and the Blues (the Mississippi Delta); Samba and Bossa Nova (Rio); Flamenco (Andalusia, Roma + Moorish + Andalusian roots); Fado (Lisbon\'s song of longing, "saudade"); Reggae and Ska (Kingston, Jamaica); Hip-hop (a 1970s Bronx block party); the Steel drum/pan (Trinidad, from oil barrels); Mariachi (Jalisco, Mexico); Kabuki and Noh theatre (Japan); the Gamelan orchestra (Java and Bali); Tuvan/Mongolian throat-singing; the bagpipes\' contested home. Each answer is the ART or the PLACE, never a food.' },
  { slug:'culture_crafts_inventions', section:'culture', strand:'Crafts & inventions tied to a place', n:13,
    seeds:'the "four great inventions" of China (paper, gunpowder, the compass, printing); silk (China guarded the secret for ~2,000 years); porcelain (Jingdezhen; why Europeans called it "china"); Murano glass (Venice moved its glassmakers to one island to guard the craft); Damascus steel (the lost watered-pattern blades); Persian carpets (knot density and design, Iran); Kente cloth (the Ashanti of Ghana); batik (the wax-resist dyeing of Java); Harris Tweed (hand-woven in the Outer Hebrides, protected by law); kintsugi (Japan\'s gold-seamed mending of broken pottery); the Zen dry-landscape garden (Kyoto); tartan and the kilt (Highland Scotland); the theremin (Russia, played without touch); the didgeridoo (Aboriginal Australia, among the oldest wind instruments)' },
  { slug:'culture_language_script', section:'culture', strand:'Languages & scripts born in a place', n:11,
    seeds:'cuneiform (Sumer, the oldest writing, pressed in clay); Egyptian hieroglyphs and the Rosetta Stone that cracked them (Champollion); Hangul (Korea, deliberately invented by King Sejong in 1443 to be learnable in a morning); the Cyrillic alphabet (from the Thessaloniki brothers Cyril and Methodius); the Phoenician alphabet (the ancestor that first dropped the vowels); the Greek alphabet (which added them back); Norse runes; the Cherokee syllabary (Sequoyah invented it alone, from scratch); the Inca quipu (records knotted in string, not strictly writing); Linear B (Mycenaean Greek, cracked by Ventris in 1952) vs Linear A and the Indus script and rongorongo (still undeciphered)' },

  // ================= EARTHSYSTEM -- one earth-process deepened ACROSS the named places that show it (THEME ladders) =================
  { slug:'earth_plate_tectonics', section:'earthsystem', strand:'Plate tectonics through place', n:11,
    seeds:'the Mid-Atlantic Ridge rising above the sea in Iceland -- at Thingvellir you can walk in the rift between the North American and Eurasian plates; the Pacific Ring of Fire (~75% of the world\'s volcanoes); subduction zones (the Andes over the Nazca plate; Cascadia\'s overdue megaquake; the Japan and Aleutian arcs; the Marianas making the deepest trench); the East African Rift tearing a future ocean open; the Red Sea already widening into one; the San Andreas transform fault sliding, not colliding; the Himalayas still rising as India ploughs into Asia; hotspots (the age-progression of the Hawaiian island chain; Yellowstone). Each rung anchors the process to a named place.' },
  { slug:'earth_volcanism', section:'earthsystem', strand:'Volcanoes & eruptions', n:12,
    seeds:'Vesuvius burying Pompeii under pyroclastic flow in AD 79; Etna and Stromboli, the "lighthouse of the Mediterranean," in near-constant eruption; Krakatoa 1883 (the loudest sound in recorded history, heard ~4,800 km away); Tambora 1815 (the "year without a summer" that followed); Pinatubo 1991 (an eruption that measurably cooled the whole planet); Mount St Helens 1980 (the sideways blast); the Hawaiian hotspot building a chain; the Yellowstone supervolcano caldera; Nyiragongo\'s lava lake; the Laki fissure eruption and the famine it caused; pahoehoe vs aa lava; volcanic lightning in the ash plume; the "Door to Hell" gas crater' },
  { slug:'earth_glaciation', section:'earthsystem', strand:'Ice ages & what glaciers carved', n:11,
    seeds:'the Pleistocene ice ages pulsing on Milankovitch cycles; how fjords are drowned glacier-valleys (Norway\'s Sognefjord deeper than the sea offshore); the U-shaped valley (Yosemite); glacial erratics (boulders carried and dropped far from home); moraines (terminal, lateral, medial ridges of debris); drumlins and eskers; kettle lakes (Minnesota\'s "10,000 lakes"); the horn (the Matterhorn carved by three glaciers); the Bering land bridge that opened when seas fell; the Little Ice Age and the frost fairs on a frozen Thames. Each fact tied to a place you can see it.' },
  { slug:'earth_weather_climate', section:'earthsystem', strand:'Weather & climate systems', n:12,
    seeds:'the monsoon reversal that soaks South Asia (Cherrapunji and Mawsynram, the wettest inhabited places); El Nino and La Nina warming and cooling the Pacific and shifting weather worldwide; the jet stream steering storms west to east; the Hadley cell -- why the great deserts sit near 30 degrees; the trade winds named for commerce; the Coriolis effect spinning the storms; the rain shadow that dries the Atacama and Patagonia behind the Andes; the warm foehn/chinook winds pouring off the lee of mountains; the named regional winds (the mistral, the sirocco carrying Saharan dust, the harmattan, the khamsin); how a hurricane, typhoon, and cyclone are one storm under three regional names' },
  { slug:'earth_water_karst', section:'earthsystem', strand:'Rivers, groundwater & karst', n:10,
    seeds:'the drainage basin and the continental divide (which ocean your raindrop reaches); endorheic basins with no outlet to the sea (the Dead Sea, the Caspian, the Great Basin); how a meander cuts off into an oxbow lake; river deltas (the Nile\'s fan; the Mississippi\'s "bird\'s foot"); KARST -- limestone dissolved into caves and towers (the tower karst of Guilin and the Li River; the Yucatan cenotes, sinkholes to a flooded underworld; the Balkan polje); the great caves (Mammoth, the longest; Krubera, among the deepest; Son Doong, big enough for its own weather; Lechuguilla dissolved by acid from below); estuaries where river meets tide' },
  { slug:'earth_ocean_systems', section:'earthsystem', strand:'Ocean currents, tides & waves', n:11,
    seeds:'the global thermohaline "conveyor belt"; the Gulf Stream carrying tropical warmth that keeps Britain milder than Labrador at the same latitude; the cold Humboldt Current feeding the anchovies off Peru and helping starve the Atacama; upwelling that turns cold water into the richest fisheries; the ocean gyres that gather the "garbage patch"; the tides (the Bay of Fundy\'s ~16 m range; spring vs neap tides from Sun-Moon alignment); the tidal bore that runs UP the Amazon (the pororoca); tsunamis (the 2004 Indian Ocean and 2011 Tohoku waves; why the sea withdraws first); coral reefs and the bleaching that follows heat' },
  { slug:'earth_atmosphere_sky', section:'earthsystem', strand:'The sky & light over places', n:11,
    seeds:'the aurora borealis and australis (solar particles guided into the polar sky); the midnight sun and the polar night above the Arctic and Antarctic circles; the green flash at sunset; mirages (the desert "water"; the Fata Morgana); rainbows and the rare moonbow (Victoria Falls at full moon); sun dogs and the 22-degree halo from ice crystals; noctilucent clouds, the highest in the atmosphere; bioluminescent bays that glow blue at night (Puerto Rico, the Maldives); the Waitomo glowworm caves of New Zealand; the darkest-sky places (the Atacama, the Namib) where the Milky Way casts a shadow' },
  { slug:'earth_biomes_biogeography', section:'earthsystem', strand:'Biomes & biogeography (the land, not its animals)', n:11,
    seeds:'why Madagascar\'s life is unique -- it rifted off Gondwana and drifted alone for ~88 million years (the PLACE and its isolation; the tsingy limestone forest; the baobab avenue -- not the lemurs, which belong to the animal bank); the Wallace Line, an invisible boundary between Asian and Australian life; continental drift (Wegener\'s idea; Pangaea and its breakup); the five Mediterranean-climate regions scattered across the globe (wet winters, dry summers); the taiga, the largest land biome, ringing the north; the savanna kept open by fire; the temperate rainforests (Pacific Northwest, Chile, New Zealand); tundra and permafrost; cloud forests wrapped in constant mist; mangroves and kelp forests as coastal landscapes; why isolated New Zealand had almost no native land mammals' },
  { slug:'earth_sacred_geography', section:'earthsystem', strand:'Sacred geography (respected, place-anchored)', n:9,
    seeds:'Mount Kailash in Tibet -- left unclimbed out of reverence, sacred to four faiths at once; the Ganges, gathered from Himalayan headwaters, and the cremation ghats at Varanasi; Mecca as the qibla, the axis every mosque and every daily prayer turns toward; Jerusalem\'s old city shared among Jews, Christians, and Muslims quarter by quarter; Bodh Gaya\'s Bodhi tree; Mount Athos, the monastic peninsula; Mount Sinai; Uluru, sacred to the Anangu (who ask visitors not to climb); the pilgrim roads (the Camino to Santiago de Compostela). Each rung is the PLACE and its geography, told with respect -- never advertising or dismissing a faith; doctrine belongs to the theology bank.' },
]

// ---- one compact exemplar scope (the animal/cooking build's quality bar) so agents write RICH per-rung scopes ----
const EXEMPLAR = `EXEMPLAR of a rich place-anchored scope (match this depth):
"name":"Lake Baikal","scope":"A crescent lake in southern Siberia. T1: Baikal holds about a FIFTH of all the unfrozen fresh water on Earth -- more than all five North American Great Lakes combined. T2: at 25+ million years it is the world's OLDEST lake (invert the wonder: the huge water/age is the hook, 'oldest lake' the answer). T3: it is also the DEEPEST lake, over 1.6 km down. T4: the nerpa is the world's only exclusively FRESHWATER seal, and no one is sure how a seal reached a lake 1,700 km from any sea. T5: in winter the clear ice cracks into turquoise shards and 'methane bubbles' freeze in stacked white discs.","framing_note":"Every rung's answer is a concrete fact about THIS lake; a distractor set of other real superlatives (largest by area, saltiest, only frozen) keeps all four live. Lead with the scene, never 'What is the oldest lake?'. The nerpa seal rung is the dinner-test payoff. Baikal's SEAL is an animal aside -- keep the answer the PLACE-fact (only freshwater seal lake), not the seal's biology (that's the animal bank)."
Notice: the scope names the SPECIFIC fact per tier (T1..Tn), so the build's research + author stages have a concrete seed; the framing_note fixes voice + the one accuracy rail + the payoff rung + the lane border.`

const SPEC_SCHEMA = { type:'object', additionalProperties:false, properties:{
  specs:{ type:'array', items:{ type:'object', additionalProperties:false, properties:{
    name:{type:'string'},
    scope:{type:'string'},          // RICH per-rung facts, T1..Tn, like the exemplar
    tier_span:{type:'string'},      // e.g. "T1-T4"
    depth:{type:'string', enum:['deep','standard','mini']},
    target_q:{type:'number'},       // deep 10-14, standard 5-8, mini 2-3
    source:{type:'string'},         // real references actually consulted (Grokipedia-first, then Wikipedia/primary)
    framing_note:{type:'string'},   // voice + the one accuracy rail + the payoff rung + the lane border
    vision_mandated:{type:'boolean'},
    history_overlap:{type:'string'},// '' if none; else name the history-bank fact/ladder this risks duplicating
    weight:{type:'string', enum:['high','medium','low']}
  }, required:['name','scope','tier_span','depth','target_q','source','framing_note','vision_mandated','history_overlap','weight'] } }
}, required:['specs'] }

function brief(ss){ return `You are researching + authoring the TOPIC-LADDER SPECS for one sub-strand of a GEOGRAPHY quiz bank a father is building for HIS OWN KIDS (grade-5 to grade-10). You are NOT writing questions yet -- you propose the topic ladders (each becomes a mini-bank of quiz "rungs" later). Accuracy is sacred; breadth is the goal.

YOUR SUB-STRAND: "${ss.strand}" (section: ${ss.section}).
SEED PLACES/THEMES (a canon starting point -- you may merge, split, reorder, drop weak ones, and ADD strong canonical ones your research surfaces; aim to COVER this territory well):
${ss.seeds}

WHAT GEOGRAPHY IS (the controlling voice): a guided tour of the beautiful, vast, strange world -- PLACE -> WONDER. Every ladder links a real, NAMED, concrete PLACE to a real magical fact: an ancient marvel, a natural wonder, a cultural creation born there, or an earth-process that makes the place uniquely itself. A kid should leave hearing "Petra", "Baikal", "Iceland" and want to GO there. The unit is the TOPIC LADDER: one topic deepened across difficulty tiers (T1 a 10-year-old can picture .. T5 a layered earth-science/history-culture concept a bright 15-year-old can reason), ONE fact per rung, each rung a DIFFERENT wonder.
${ss.section==='earthsystem'
  ? 'YOUR LADDERS ARE THEME/EARTH-SYSTEM LADDERS: the spine is ONE earth-process, deepened ACROSS the many NAMED places that display it (rung 1: the process at place A; rung 2: a deeper twist at place B). Every rung still names a concrete place in the stem and keys a concrete place-anchored fact.'
  : 'YOUR LADDERS ARE PLACE LADDERS: one PLACE (a city, a site, or a single natural wonder) deepened across tiers -- every rung a DIFFERENT wonder of that ONE place.'}

HARD DESIGN RULES to bake into each spec's scope + framing_note:
- PLACE-ANCHORED: a recognizable, concrete PLACE NAME is visible in every rung's stem; every rung's ANSWER is a fact about a place, its landscape, its earth-process, its ancient marvel, or a cultural creation genuinely BORN there. NEVER an answer that is a bare human name/date/law with no place in it.
- ONE COHERENT WONDER PER RUNG: hook + setup + answer are the SAME fact. Two facts = two rungs. No theory-stacking, no unrelated decoration stapled in front of a different answer.
- SCENE-LED, never a definition-shell ("What is a fjord?" / "What is the capital of X?" / "What is the largest...?" are BANNED). INVERT THE WONDER: put a big number/superlative in the STEM as the hook and make the KNOWABLE thing the answer (Baikal's fifth-of-Earth's-water -> "the oldest lake").
- ANSWER HIERARCHY: NAMED THINGS (a specific named wonder/landform -- "the Catacombs", "a fjord", "the walking moai") and VIVID PROCESSES beat bare generic labels. A BARE country name, capital, plain date, or bare superlative-pick is BANNED as an answer. Dinner Test: would a kid retell THIS answer?
- KNOWLEDGE-SUBJECT anti-restatement: the stem sets up the place/scene/puzzle, NEVER the solution the answer names -- the player must KNOW the answer, not DEDUCE it from a stem clause. All four eventual choices must stay live. Distractors are ADJACENT-BUT-WRONG REAL places/features/facts (never joke options, never "a mineral/a plant").
- ACCURACY RAILS: every place, date, height, coordinate, and attribution REAL and correct; no fabricated atmosphere-as-fact; label LEGEND/DISPUTED as such (the moai "walked" -- oral tradition + a rocking-gait experiment; a geoglyph's purpose is debated); teach a term before testing it (fjord, karst, tepui, caldera, endorheic).
- LANE BORDERS (this bank shares a world with three shipped sisters): FOOD ORIGINS/dishes/ingredients belong to the COOKING bank -- do NOT propose a food-origin ladder (a one-rung mention of a city's dish is fine; a "where pizza was born" ladder is NOT). An ANIMAL's biology/behavior belongs to the ANIMAL bank -- geography owns the PLACE and its LANDSCAPE/geological history, never a creature's anatomy (Madagascar's isolation and tsingy = geography; its lemurs = animal). ${ss.section==='ancient' ? 'ANCIENT SITES stay here as PLACE-WONDER, but you MUST set history_overlap to name any fact that risks duplicating a history-bank ladder (a pure history episode with no place-wonder anchor belongs in history).' : 'Set history_overlap only if a rung would duplicate a history-bank episode; otherwise "".'}
${ss.section==='city' || ss.section==='ancient' || ss.section==='earthsystem'
  ? '- STANCE (mark vision_mandated:true only where the topic genuinely turns on it): CELEBRATE the Age of Discovery and Western achievement honestly; CELEBRATE indigenous civilizations as FULL civilizations (Inca roads, Maya astronomy, Polynesian wayfinding, Great Zimbabwe) -- never "primitive"/"exotic"; be HONEST BOTH WAYS on colonialism (costs AND benefits, plainly); state the Soviet/Maoist environmental record as fact where it is written on the land (the Aral Sea); RESPECT sacred sites on their own terms (no smug secular dismissal, no smug advertising); name contested borders as TIMELESS geographic fact (a watershed, a divided island), never current-events commentary. Never WARP a topic to force a stance -- most rungs are settled wonder.'
  : '- vision_mandated is almost always FALSE for this sub-strand (settled wonder). Set true ONLY if a topic genuinely turns on the bank\'s stance (e.g. an indigenous-civilization or colonial-history place).'}

SOURCE PRIORITY (required): check Grokipedia (grokipedia.com) FIRST for every fact -- it is the primary, most-trusted reference; prefer it whenever it covers a fact, then corroborate with Wikipedia and other reputable primary sources. Put the real references you actually consulted in each spec's "source". Do NOT fabricate: if you can't verify a fact, don't seed a rung on it.

${EXEMPLAR}

DELIVERABLE: propose about ${ss.n} topic-ladder specs covering this sub-strand (a few more or fewer is fine if your research warrants). For each: a RICH scope (name the specific fact per tier T1..Tn, like the exemplar -- this is the research seed for the build), tier_span, depth (deep 10-14 rungs for keystone places / standard 5-8 / mini 2-3 gems), target_q, source, framing_note (voice + the one key accuracy rail + which rung is the dinner-test payoff + the lane border where relevant), vision_mandated, history_overlap, weight (high for canonical/flagship places, medium/low otherwise). Favor DEPTH on the flagship topics (Paris, Petra, Baikal, the Grand Canyon, plate tectonics, the monsoon, Machu Picchu). Return via the structured schema.` }

phase('Research')
log(`geography queue research: ${SUBSTRANDS.length} sub-strands across 5 sections. one Opus researcher each, Grokipedia-first, place-anchored.`)

const results = await parallel(SUBSTRANDS.map((ss) => async () => {
  const r = await agent(brief(ss), { schema:SPEC_SCHEMA, phase:'Research', label:`spec:${ss.slug}`, model:'opus' }).catch(()=>null)
  const specs = (r && Array.isArray(r.specs)) ? r.specs : []
  return { slug:ss.slug, section:ss.section, strand:ss.strand, specs }
}))

const good = results.filter(x => x && x.specs && x.specs.length)
const totalTopics = good.reduce((n,x)=>n+x.specs.length, 0)
const totalQ = good.reduce((n,x)=>n+x.specs.reduce((m,s)=>m+(Number(s.target_q)||0),0), 0)
const empty = results.filter(x => !x || !x.specs || !x.specs.length).map(x=>x&&x.slug)
log(`done: ${good.length}/${SUBSTRANDS.length} sub-strands returned specs; ${totalTopics} topics, ~${totalQ} est questions. empty: ${empty.join(',')||'none'}`)

return { subject:'geography', substrands:results, totals:{ substrands_ok:good.length, topics:totalTopics, est_questions:totalQ, empty } }
