export const meta = {
  name: 'cooking-queue-research',
  description: 'Research + author the cooking bank v2 topic queue: one Opus researcher per sub-strand across the six strands (kitchen/ingredient/recipe/history/wonder/nutrition), Grokipedia-first, returns richly-scoped topic ladders.',
  phases: [
    { title: 'Research', detail: 'one researcher per sub-strand -> rich topic-ladder specs' },
  ],
}

// ---- the six strands, split into focused sub-strands with seed topics (canon breadth). ----
// Each agent proposes ~10-14 topic LADDERS for its sub-strand, adding/merging beyond the seeds as its
// research warrants. section+strand are injected on write (fixed per sub-strand), so the agent omits them.
const SUBSTRANDS = [
  // ---------- (1) IN THE KITCHEN — technique/tools/safety, mechanism as the lens ----------
  { slug:'kitchen_knife', section:'kitchen', strand:'Knife skills & cutting',
    seeds:'the claw grip & why a sharp knife is safer than a dull one; the basic cuts (dice/mince/slice/chop); the French precision cuts (julienne/brunoise/chiffonade/batonnet) — shape & size; sharpening on a whetstone vs realigning on a honing steel; parts of the chef\'s knife & what each does; why you never catch a falling knife; the right cutting board & board hygiene; rocking vs push-cutting; why you cut away from your hand' },
  { slug:'kitchen_heat', section:'kitchen', strand:'Heat & the browning reaction',
    seeds:'dry heat (sear/roast/grill/broil/fry) vs wet heat (braise/stew/steam/poach/simmer) — which for which cut; the sear→Maillard-browning→fond→deglaze thread; why "searing seals in juices" is a MYTH (it browns for flavor); don\'t-crowd-the-pan (steaming vs browning); simmer vs a rolling boil; carryover cooking & resting meat; caramelization vs Maillard (sugar alone vs sugar+protein); oil smoke points (why olive vs avocado vs butter); why a screaming-hot pan; reduction & concentrating flavor' },
  { slug:'kitchen_safety', section:'kitchen', strand:'Food safety & the danger zone',
    seeds:'wash hands 20s & when; the 40–140°F danger zone (why bacteria love it); raw-chicken protocol (don\'t rinse — it splashes; separate board; sanitize); cross-contamination as how outbreaks start; safe internal temps (chicken 165, ground beef 160, pork 145, why); the big foodborne pathogens as CONCEPTS (salmonella=poultry/eggs, E. coli=ground beef/greens, listeria=deli/soft cheese); safe thawing (fridge/cold water/microwave, never the counter); best-by (quality) vs use-by (safety); clean vs sanitize' },
  { slug:'kitchen_fundamentals', section:'kitchen', strand:'Kitchen fundamentals & ratios',
    seeds:'mise en place (everything in its place before the burner); salt as the great flavor-amplifier & WHEN to salt; the emulsion trick (vinaigrette/mayo/hollandaise — fat suspended in water by an emulsifier, why it "breaks"); the useful ratios (rice ~1:2, pasta water "salty as the sea", vinaigrette 3:1 oil:acid, why); why you save pasta water (starch binds the sauce); scaling a recipe (baking times don\'t scale linearly); the cookware line-up (cast iron / stainless / nonstick / carbon steel — each pan\'s job); why acid brightens a dish; deglazing to build a pan sauce' },
  { slug:'kitchen_baking', section:'kitchen', strand:'Baking is chemistry',
    seeds:'the leaveners (yeast=living CO2 vs baking soda=needs acid vs baking powder=self-contained vs steam vs whipped egg) — which does what; gluten development (why you knead bread but barely stir a muffin); the creaming method (why beat butter & sugar); lamination (croissant\'s hundreds of butter layers puff into flakes) as a concept; proofing & the poke test; why baking is measured not eyeballed; why bread goes stale then revives in the oven (starch retrogradation, as a concept); what an egg does in a batter (bind/leaven/enrich); why salt controls yeast' },

  // ---------- (2) INGREDIENTS — provenance: where food comes from ----------
  { slug:'ingredient_meat', section:'ingredient', strand:'Cuts of meat & the animal',
    seeds:'why chuck/shoulder is tough but ribeye/loin is tender (hard-working muscle & collagen vs lazy muscle & fat); why tough cuts need low-and-slow (collagen melts to gelatin); the beef primals (where chuck/rib/loin/round sit on the steer); pork (shoulder→pulled pork, belly→bacon, loin→chops); why cure & smoke meat (salt draws water, preserves); dry-aging vs wet-aging; offal / nose-to-tail (liver, kidney, tongue, sweetbreads — what they are); why you rest & slice against the grain; ground meat & why it must cook through; poultry (dark vs white meat = working vs still muscle) [prep-frame OK, matter-of-fact tone]' },
  { slug:'ingredient_seafood', section:'ingredient', strand:'Fish & seafood provenance',
    seeds:'wild-caught vs farmed (and why it matters); oily fish (salmon/sardine/mackerel) vs lean white fish (cod/haddock) — why the fat, why the flavor; why bivalves (oyster/mussel/clam) filter-feed & spoil fast; shrimp/prawn/lobster/crab (crustaceans, why they turn red cooked — astaxanthin freed by heat); roe & caviar (what it is); why sushi-grade fish is flash-frozen (kills parasites); the fishmonger\'s freshness cues (clear eyes, no "fishy" smell = fresh); squid & octopus as food (why they turn rubbery then tender); why some fish flesh is pink (diet) vs white' },
  { slug:'ingredient_produce', section:'ingredient', strand:'What part of the plant we eat',
    seeds:'the botanical surprise: tomato/cucumber/pepper/eggplant/avocado/pumpkin are FRUITS (seed-bearing); broccoli & cauliflower are unopened FLOWER buds; asparagus is a young STEM; carrot/beet/radish are ROOTS; celery/rhubarb are STALKS/petioles; a potato is a TUBER (swollen stem) but a sweet potato is a ROOT; onion/garlic are BULBS; a peanut is a LEGUME that ripens underground; ginger/turmeric are RHIZOMES; kale/cabbage/broccoli/brussels sprouts are all one species (Brassica oleracea); where staples actually grow' },
  { slug:'ingredient_grains', section:'ingredient', strand:'Grains, corn & bread-stuffs',
    seeds:'a wheat kernel (bran/germ/endosperm) & what milling removes (white vs whole); why bread flour vs cake flour (protein=gluten); rice (long-grain stays separate vs short-grain sticks; why); corn/maize & the nixtamalization complex (soaking in alkali unlocks niacin/B3, prevents pellagra) → masa → the tortilla/tamale; oats (rolled vs steel-cut); the "founding crops" of farming; legumes (beans/lentils/chickpeas) as protein + the Three Sisters (corn-beans-squash); why you soak dried beans; quinoa (a complete-protein seed)' },
  { slug:'ingredient_spices', section:'ingredient', strand:'Spices & herbs: where they grow',
    seeds:'black pepper is a dried unripe berry (drupe) from an Indian vine; cinnamon is the inner BARK of a tree (Sri Lanka); nutmeg & mace are two spices from ONE seed (Banda Islands); vanilla is the cured pod of an orchid, hand-pollinated (Edmond Albius, a 12-yr-old enslaved boy, invented the trick); saffron is the hand-picked stigma of a crocus (~150,000 flowers/lb); cloves are dried flower buds; chili heat is capsaicin (Scoville scale); herb (leaf) vs spice (seed/bark/root/bud); why you toast/bloom whole spices; where paprika/cumin/cardamom come from' },
  { slug:'ingredient_dairyfat', section:'ingredient', strand:'Dairy, eggs, fats & sweeteners',
    seeds:'milk → cream → butter (churning breaks the fat emulsion) → and buttermilk; how cheese is made (rennet or acid curdles milk; whey drains; aging); yogurt (fermented milk); what an egg is (yolk=fat+emulsifier, white=protein) & why it binds and leavens; where oils come from (olive = pressed fruit; seed/vegetable oils = extracted from seeds; animal fats = rendered lard/tallow; ghee = clarified butter); honey (bees reduce nectar; why it never spoils); sugar (cane vs beet, how refined; molasses); salt (evaporated sea vs mined rock); maple syrup (~40 gal sap boiled to 1 gal)' },

  // ---------- (3) RECIPES — dish literacy: what a classic dish is + its core technique ----------
  { slug:'recipe_french', section:'recipe', strand:'French classics',
    seeds:'the five MOTHER sauces (béchamel/velouté/espagnole/tomato/hollandaise) — what each is built on (Carême & Escoffier); Beef Wellington (fillet + mushroom duxelles + prosciutto + puff pastry — the duxelles barrier keeps the crust from going soggy); coq au vin & boeuf bourguignon (braise in red wine); the soufflé (whipped egg white puffs then collapses); confit (poach & preserve in fat); the French omelette (no browning, soft curd); crème brûlée (torched sugar crust); croissant lamination; what "à la" / "en croûte" mean; ratatouille' },
  { slug:'recipe_italian', section:'recipe', strand:'Italian',
    seeds:'why pasta shapes match sauces (ridges/tubes grab chunky sauce, strands suit oil/cream); authentic ragù alla bolognese (Bologna; meat + soffritto + milk + a little wine; served with TAGLIATELLE not spaghetti — "spaghetti bolognese" isn\'t Italian); risotto (toast the rice, stir to release starch, creamy without cream); carbonara (egg + pecorino + guanciale + pasta water — NO cream); cacio e pepe (an emulsion of cheese, pepper, starchy water); Pizza Margherita (1889 Naples, tricolor for the Queen); the North-butter-&-egg-pasta / South-oil-&-durum divide; gnocchi (potato ones are post-Columbian); pesto (pounded in a mortar)' },
  { slug:'recipe_east_asian', section:'recipe', strand:'East Asian dishes',
    seeds:'the wok & "wok hei" (breath of the wok — high heat + toss gives a smoky char); Chinese regional (Sichuan má-là numbing-heat from Sichuan pepper + chili; Cantonese fresh steaming & seafood; Hunan); dashi (kombu kelp + bonito flakes = the umami base of Japanese cooking); sushi began as PRESERVATION (narezushi — fermented rice + fish) → modern nigiri (Edo street food); ramen; Korean BBQ + banchan; kimchi as a dish (salted, spiced, lacto-fermented cabbage); Peking duck (the lacquered skin); dim sum; stir-fry logic (prep everything, cook fast, hot); soy sauce & miso as fermented backbones' },
  { slug:'recipe_south_se_asian', section:'recipe', strand:'South & SE Asian dishes',
    seeds:'Indian curry & the tadka/tempering (bloom whole spices in hot ghee to release fat-soluble flavor); Vindaloo (from Portuguese "carne de vinha d\'alhos" = meat in wine-vinegar & garlic → Goa swapped in palm vinegar & chili); the tandoor (clay oven → naan & tandoori); dal (lentils); biryani (layered rice + meat); regional India (North: wheat/dairy/tandoor vs South: rice/coconut/sambar); Thai balance of sweet-sour-salty-spicy in one dish; the Thai curry pastes (green/red/massaman — different chilies & aromatics); pho (Vietnamese beef-bone broth, French + Chinese influence); banh mi (French baguette + Vietnamese fillings); pad thai' },
  { slug:'recipe_latin', section:'recipe', strand:'Mexican & Latin American dishes',
    seeds:'mole (Puebla\'s mole poblano — dozens of ingredients incl. chilies & chocolate, ground to a sauce; vs Oaxaca\'s black mole); the masa complex (nixtamalized corn → tortilla, tamale, sope); ceviche (acid "cooks" fish by denaturing proteins, no heat); the chili family (jalapeño→chipotle when smoked; poblano; habanero; scoville); guacamole; Argentine asado & chimichurri; Brazilian feijoada (black beans + pork); arepas; al pastor (Lebanese shawarma spit → Mexico City) ; why the chili is originally Mexican and remade world cuisine' },
  { slug:'recipe_medit_mideast_africa', section:'recipe', strand:'Mediterranean, Middle Eastern & African dishes',
    seeds:'hummus & tahini (chickpea purée + sesame paste; the origin claimed across the Levant); the mezze table; Moroccan tagine (the conical clay pot traps steam) & couscous (steamed semolina); Ethiopian injera (spongy sourdough teff flatbread you eat WITH, as the utensil) & the shared platter; West African jollof rice (the friendly Nigeria-vs-Ghana rivalry); Greek moussaka & the olive-oil base; shawarma/döner/gyro (the vertical spit); falafel; the spice blends (ras el hanout, za\'atar, harissa, berbere); the global flatbread family (pita/lavash/naan/injera)' },
  { slug:'recipe_us_uk', section:'recipe', strand:'American & British regional dishes',
    seeds:'the four BBQ regions (Texas beef brisket; Carolina vinegar-pork; Kansas City sweet sauce; Memphis dry rub — all "low & slow" smoke breaking down collagen); gumbo & the roux (West African okra + French roux + Cajun/Creole Louisiana); soul food origins; the British Sunday roast + Yorkshire pudding (batter cooked in beef drippings); chowder (New England cream vs Manhattan tomato — the feud); the pie (savory & sweet); mac & cheese (a béchamel); the sandwich (John Montagu, 4th Earl of Sandwich, 1762, at the gambling table); fish & chips; jambalaya vs paella' },

  // ---------- (4) FOOD HISTORY — world history through food, drama-led (answer always food-anchored) ----------
  { slug:'history_ancient', section:'history', strand:'How cooking made the world (ancient)',
    seeds:'cooking made us human (Richard Wrangham — fire + cooked food unlocked calories, shrank the gut, grew the brain); the first breads (Natufian flatbread ~14,000 yrs ago, BEFORE farming); the Agricultural Revolution & the founding crops (Fertile Crescent wheat/barley/lentil); beer & bread grew up together in Mesopotamia; Roman food (garum — the fermented fish sauce Romans put on everything; bread & the grain dole "bread and circuses"); salt\'s ancient power ("salary," salt roads); the domestication of the first food animals' },
  { slug:'history_spice', section:'history', strand:'Spice & the age of exploration',
    seeds:'spices were worth a fortune (preservation + status + medicine) and DROVE European exploration; nutmeg & cloves came ONLY from the tiny Banda/Maluku "Spice Islands"; the Dutch VOC massacre of the Bandanese in 1621 to monopolize NUTMEG (and later swapped Manhattan for the nutmeg island Run); pepper from India, cinnamon from Sri Lanka; Columbus was hunting a spice route to the Indies when he hit America; why a pinch of pepper once cost a day\'s wage; the caravans & the sea-route race (da Gama)' },
  { slug:'history_columbian', section:'history', strand:'The Columbian Exchange',
    seeds:'the great swap after 1492 (Americas → world: potato, tomato, chili, maize, chocolate, vanilla, turkey, beans, squash; Old World → Americas: wheat, sugar, cattle, pigs, citrus, coffee, bananas); the humble POTATO remade Europe (cheap calories → population boom → and vulnerability); the tomato reached Italy only in the 1500s (feared as poisonous at first); the chili conquered Indian/Thai/Sichuan cooking (all post-Columbian); chocolate went from bitter Aztec ritual drink to sweet European treat; the Irish Potato Famine (one blight + one clone-variety monoculture + landlord/export policy → ~1M dead, ~1M fled) — food-anchored drama' },
  { slug:'history_feast', section:'history', strand:'The feast & the table through time',
    seeds:'the medieval banquet as spectacle (trenchers = stale-bread "plates"; seating "above/below the salt" by rank; the roasted peacock or swan re-dressed in its own feathers; the boar\'s head); "subtleties" (edible sugar/marzipan sculptures paraded between courses); the Roman convivium (reclining to eat; the "vomitorium" was an ARCHWAY, not a purging room — myth-bust); Versailles & Louis XIV\'s public dining as theatre ("le grand couvert"); service à la française (everything at once) → service à la russe (~1810, plated courses in sequence — modern dining); the first "restaurant" (Boulanger, Paris 1765, a "restorative" broth); the French Revolution scattered aristocrats\' chefs into public restaurants' },
  { slug:'history_preservation', section:'history', strand:'Preserving & the industrial food revolution',
    seeds:'before the fridge: salting, smoking, drying, and fermenting kept people alive through winter; canning — Nicolas Appert won Napoleon\'s 12,000-franc prize (1809) for sealing food in jars ("an army marches on its stomach"), before anyone knew WHY it worked; Pasteur (1864) explained it & gave us pasteurized milk; refrigeration & the railway cold-chain centralized meatpacking in Chicago; Clarence Birdseye\'s flash-freezing (1924, inspired by Inuit ice-fishing); sliced/wrapped bread ("the greatest thing since…", 1928); how these changed the family dinner' },
  { slug:'history_chefs', section:'history', strand:'The people who invented modern cuisine',
    seeds:'Marie-Antoine Carême — the first "celebrity chef," master of grande cuisine & showpiece pièces montées, cooked for Talleyrand & tsars (and the tall toque story); Auguste Escoffier — invented the kitchen "brigade" system (stations & hierarchy) and simplified/codified French cooking; Brillat-Savarin — "Tell me what you eat and I\'ll tell you what you are" (The Physiology of Taste, 1825); Fannie Farmer — standardized the level measuring cup/spoon (1896) so recipes finally worked; Julia Child — brought real French technique to American home kitchens; how a restaurant earns Michelin stars' },

  // ---------- (5) AMAZING FACTS — the wonder well ----------
  { slug:'wonder_secretly', section:'wonder', strand:'Foods that are secretly something surprising',
    seeds:'the passion fruit is named for the PASSION OF CHRIST — 16th-c. missionaries read the Crucifixion in the flower (corona = crown of thorns); a peanut is a LEGUME that ripens underground, not a nut; cashews hang off the bottom of a "cashew apple" and the raw shell is caustic (same family as poison ivy) — why you never see a raw cashew in its shell; a fig is an inside-out flower pollinated by a tiny wasp; vanilla is an orchid pod; a pineapple is dozens of berries fused into one; almonds are the pit of a peach-relative (and bitter wild almonds carry cyanide); a banana is a berry but a strawberry isn\'t; broccoli/kale/cabbage/brussels sprouts are ONE species bred differently' },
  { slug:'wonder_senses', section:'wonder', strand:'The senses & why food tastes that way',
    seeds:'the five basic tastes incl. UMAMI (Ikeda isolated glutamate from kombu, 1908); why cilantro tastes like SOAP to some people (a smell-receptor gene variant); capsaicin fools the heat-sensor TRPV1 (your mouth "burns" with no actual heat) — so MILK, not water, cures it (fat-soluble; casein lifts it off); why chopping ONIONS makes you cry (broken cells release a sulfur gas that becomes acid in your eyes); Sichuan pepper\'s tingle (a molecule that literally vibrates your touch nerves ~50x/sec); the "miracle berry" that makes sour taste sweet; why coffee/dark beer are "acquired" tastes; supertasters' },
  { slug:'wonder_extreme', section:'wonder', strand:'The most extreme foods on Earth',
    seeds:'the priciest — why saffron, white Alba truffle, wagyu/Kobe beef, and beluga caviar cost fortunes (hand-labor, rarity, marbling, roe from old fish); the strangest fermented — surströmming (Swedish fermented herring, opened outdoors), century egg, casu marzu (the Sardinian cheese with live fly larvae), Icelandic hákarl (fermented shark); durian — the fruit BANNED on trains & planes for its smell (the sulfur/ester chemistry); the world\'s hottest peppers on the Scoville scale (Carolina Reaper → Pepper X); balut; foods that take YEARS (aged balsamic, 24-month Parmigiano) — invert the wonder (put the number in the stem)' },
  { slug:'wonder_fermentation', section:'wonder', strand:'The magic of fermentation',
    seeds:'invisible microbes transform food — the same trick behind cheese, bread, beer, wine, yogurt, kimchi, soy sauce, chocolate & coffee; milk → cheese/yogurt (bacteria sour it, rennet sets it); cabbage → sauerkraut/kimchi (salt holds back rot while lactic-acid bacteria do the work); grapes → wine & grain → beer (yeast eats sugar, makes alcohol + CO2) — both ancient; soybeans → miso/soy/tempeh; the cacao bean MUST ferment in its own pulp before it can taste of chocolate; coffee cherries are fermented to free the bean; sourdough (wild yeast + lactobacillus; why San Francisco\'s tang is local); fermentation both PRESERVES and CREATES flavor' },
  { slug:'wonder_chemistry', section:'wonder', strand:'Chemistry you can taste',
    seeds:'why a seared steak smells & tastes so good (the Maillard reaction spins out hundreds of new aroma compounds — Louis-Camille Maillard, 1912); why a loaf\'s crust is brown & the crumb stays pale; why cut apples & avocados go brown (enzyme + oxygen) and why lemon juice stops it; why a pinch of salt makes sweet things taste sweeter (and suppresses bitter); cooking makes some foods MORE nutritious (tomato lycopene, spinach iron) and destroys others (vitamin C); why resting meat keeps it juicy; why stale bread crisps back up in the oven; foams & spherification (modernist cuisine)' },

  // ---------- (6) NUTRITION — what food does in your body; traditional-foods lean ----------
  { slug:'nutrition_macros', section:'nutrition', strand:'Macros: why your body needs them',
    seeds:'PROTEIN builds & repairs (muscle, enzymes, antibodies) — why RED MEAT is a "complete" protein with all essential amino acids PLUS heme iron & B12; complete vs incomplete (why beans+rice together); FATS are not the enemy — energy, cell membranes, hormones, and the CARRIER for fat-soluble vitamins; saturated vs mono vs poly; omega-3 vs omega-6 balance; CARBS are fuel (simple vs complex) and the source of FIBER; why fiber feeds your gut & slows sugar; why a growing kid/athlete needs more protein; what each macro\'s job actually is' },
  { slug:'nutrition_micros', section:'nutrition', strand:'Micros: vitamins & where you get them',
    seeds:'vitamin A (liver, egg yolks, and orange veg via beta-carotene — for eyes, skin, immunity; why the "carrots for night vision" story is half-true); vitamin C (citrus/peppers — scurvy & why the Royal Navy carried limes); vitamin D (sunlight + fatty fish); iron — HEME (red meat, absorbs well) vs NON-heme (plants, absorbs poorly, helped by vitamin C); calcium (dairy & leafy greens); B12 (only reliably from animal foods — why vegans supplement); the fat-soluble A/D/E/K need dietary FAT to absorb (so eat the butter with the veg); why VARIETY beats any single "superfood"' },
  { slug:'nutrition_whole_gut', section:'nutrition', strand:'Whole vs processed, and your gut',
    seeds:'what "ultra-processed" means (the NOVA group-4 idea — foods built from industrial ingredients & additives) and the honest state of the evidence (the health correlations are real; the mechanism is debated) — lean: whole foods generally win; fermented foods & the GUT MICROBIOME (why a diverse gut matters, what probiotics are); FIBER as fuel for gut bacteria; ADDED sugar (WHO ~<5–10% of calories; why it hides under 50 names); a practical heuristic (if the label reads like a chemistry set…); why "eat food, mostly plants, not too much" is decent advice' },
  { slug:'nutrition_debates', section:'nutrition', strand:'The great nutrition debates', vision:true,
    seeds:'SEED OILS — the omega-6/inflammation & heated-oil-aldehyde worry vs the mainstream "PUFA lowers LDL, is heart-healthy" view (lean: skeptical of heated/reused industrial seed oils, honest about the mainstream case); RAW MILK — proponents (enzymes, probiotics, fewer allergies) vs FDA pathogen risk; the SATURATED-FAT reversal (old "artery-clogging" guidance vs 2010s re-examination); CHOLESTEROL revisionism (dietary cholesterol\'s small effect; the 2015 USDA reversal); ANCESTRAL diets (paleo/keto/carnivore as schools); ORGANIC (pesticide-reduction firm, nutrition-boost contested); NON-CELIAC gluten. STEEL-MAN both sides; the correct answer fairly SUMMARIZES the debate or states the traditional-foods case honestly; distractors caricature either side' },
  { slug:'nutrition_balanced', section:'nutrition', strand:'Building a diet that fits your goals',
    seeds:'what a balanced PLATE looks like (protein + vegetables + smart carbs + fats); protein needs for building muscle & growing; NUTRIENT DENSITY (the most nutrition per calorie — liver, eggs, fish, leafy greens — vs "empty calories"); why TRADITIONAL diets are useful models (the Mediterranean pattern — olive oil, fish, vegetables; the "Blue Zones"; the Weston A. Price traditional-foods principles — fermented foods, organ meats, whole-fat dairy); hydration; eating for energy vs for growth vs for recovery; the idea that "food is information for your body" — tailoring what you eat to your OWN goals' },
]

// ---- one compact exemplar scope (the animal build's quality bar) so agents write RICH per-rung scopes ----
const EXEMPLAR = `EXEMPLAR of a rich scope (from the shipped animal bank — match this depth, adapted to cooking):
"name":"Focusing light underwater","scope":"The problem: underwater a cornea can't bend light, so aquatic eyes focus with the lens alone. T1: a fish's eye lens is a hard near-perfect SPHERE (not the squishy disc land animals have). T2: fish focus by MOVING the whole rigid lens back and forth, like sliding a projector lens, instead of squeezing it. T3: the octopus, on a totally separate branch, built the SAME spherical-lens eye it also moves to focus (convergent evolution). T4: the fish lens fixes blur with a graded refractive index, denser in the center.","framing_note":"Every rung's answer is a concrete eye-mechanics fact about a specific animal. Lead with the scene, never 'What is a lens?'. The octopus rung is the dinner-test payoff."
Notice: the scope names the SPECIFIC fact per tier (T1..Tn), so the build's research + author stages have a concrete seed; the framing_note fixes voice + the one accuracy rail + the payoff rung.`

const SPEC_SCHEMA = { type:'object', additionalProperties:false, properties:{
  specs:{ type:'array', items:{ type:'object', additionalProperties:false, properties:{
    name:{type:'string'},
    scope:{type:'string'},          // RICH per-rung facts, T1..Tn, like the exemplar
    tier_span:{type:'string'},      // e.g. "T1-T4"
    depth:{type:'string', enum:['deep','standard','mini']},
    target_q:{type:'number'},       // deep 10-14, standard 5-8, mini 2-3
    source:{type:'string'},         // real references actually consulted (Grokipedia-first, then Wikipedia/primary)
    framing_note:{type:'string'},   // voice + the one accuracy rail + the payoff rung, per the design
    vision_mandated:{type:'boolean'},
    weight:{type:'string', enum:['high','medium','low']}
  }, required:['name','scope','tier_span','depth','target_q','source','framing_note','vision_mandated','weight'] } }
}, required:['specs'] }

function brief(ss){ return `You are researching + authoring the TOPIC-LADDER SPECS for one sub-strand of a COOKING quiz bank a father is building for HIS OWN KIDS (grade-5 to grade-10). You are NOT writing questions yet — you are proposing the topic ladders (each becomes a mini-bank of quiz "rungs" later). Accuracy is sacred; breadth is the goal.

YOUR SUB-STRAND: "${ss.strand}" (strand section: ${ss.section}).
SEED TOPICS (a canon starting point — you may merge, split, reorder, drop weak ones, and ADD strong canonical topics your research surfaces; aim to COVER this territory well):
${ss.seeds}

WHAT COOKING IS (the controlling voice): food KNOWLEDGE + WONDER a kid can USE. Every ladder reveals a MECHANISM (why searing browns), an ORIGIN / where a food comes from, a DISH's defining technique, a food-driven HISTORICAL beat, an amazing FACT, or an honest NUTRITION truth. The unit is the TOPIC LADDER: one topic deepened across difficulty tiers (T1 a 10-year-old can know/reason .. T5 a concept a bright 15-year-old can reason), ONE fact per rung, each rung a DIFFERENT payoff.

HARD DESIGN RULES to bake into each spec's scope + framing_note:
- FOOD-ANCHORED ANSWER: every rung's eventual ANSWER is about food/cooking/an ingredient/a technique/a dish/a food-driven payoff — NEVER a bare law, policy, agency, or a human name/date with no food in it. (Food-driven history where the FOOD is the anchor — the Banda nutmeg wars, the potato famine's blight — is great; food-aid geopolitics is NOT.)
- ONE COHERENT POINT PER RUNG: hook + setup + answer are the SAME fact. Two facts = two rungs.
- SCENE-LED, never a definition-shell ("What is X?" is banned). INVERT THE WONDER: put a big number/superlative in the STEM as the hook and make the KNOWABLE thing the answer (saffron → the crocus).
- KNOWLEDGE-SUBJECT anti-restatement: the stem sets up the dish/scene/puzzle, NEVER the solution the answer names — the player must KNOW the answer, not DEDUCE it from a stem clause. All four eventual choices must stay live.
- BANNED MINUTIAE as the tested answer: exact numbers/yields/percentages, microbe/enzyme Latin names, lab jargon, production statistics, pre-ferment names. Teach the CONCEPT; a number/microbe may be a distractor or context only.
- ACCURACY RAILS: no anachronisms (no tomato in Italy pre-1500, no chili in Asia pre-Columbus, no universal fork-dining pre-18th c.); correct attributions (potato=Andean, tomato=Mexican, Bolognese=with tagliatelle); label legend as legend.
- PREP-FRAME is FINE for cooking (the game action is cooking) — a "you sear/knead/cut it" voice is OK; keep butchery/offal wording matter-of-fact for a kid, never gory.
${ss.section==='nutrition' ? '- NUTRITION STANCE: the bank LEANS TRADITIONAL-FOODS — steel-man BOTH sides, never strawman the mainstream, but lean skeptical of ultra-processed / heated-seed-oil orthodoxy and sympathetic to whole/traditional/fermented foods; empowerment not moralizing (a kid should understand WHY they need red meat, what fats DO, where vitamin A is). Mark contested-debate topics vision_mandated:true; settled nutrition (macros exist, scurvy=vitamin C) is vision_mandated:false.' : '- vision_mandated is almost always FALSE for this sub-strand (settled/practical/wonder content). Set true ONLY if a topic genuinely turns on the bank\'s stance.'}

SOURCE PRIORITY (required): check Grokipedia (grokipedia.com) FIRST for every fact — it is the primary, most-trusted reference; prefer it whenever it covers a fact, then corroborate with Wikipedia and other reputable primary sources. Put the real references you actually consulted in each spec's "source". Do NOT fabricate: if you can't verify a fact, don't seed a rung on it.

${EXEMPLAR}

DELIVERABLE: propose ${ss.section==='history'||ss.section==='wonder' ? '10-13' : '10-14'} topic-ladder specs covering this sub-strand. For each: a RICH scope (name the specific fact per tier T1..Tn, like the exemplar — this is the research seed for the build), tier_span, depth (deep 10-14 rungs for keystone topics / standard 5-8 / mini 2-3 gems), target_q, source, framing_note (voice + the one key accuracy rail + which rung is the dinner-test payoff), vision_mandated, weight (high for canonical/flagship, medium/low otherwise). Favor DEPTH on the flagship topics (the sear/Maillard thread, the mother sauces, the Columbian Exchange, cuts of meat, fermentation, the great nutrition debates). Return via the structured schema.` }

phase('Research')
log(`cooking queue research: ${SUBSTRANDS.length} sub-strands across 6 strands. one Opus researcher each, Grokipedia-first.`)

const results = await parallel(SUBSTRANDS.map((ss) => async () => {
  const r = await agent(brief(ss), { schema:SPEC_SCHEMA, phase:'Research', label:`spec:${ss.slug}`, model:'opus' }).catch(()=>null)
  const specs = (r && Array.isArray(r.specs)) ? r.specs : []
  return { slug:ss.slug, section:ss.section, strand:ss.strand, specs }
}))

const good = results.filter(x => x && x.specs && x.specs.length)
const totalTopics = good.reduce((n,x)=>n+x.specs.length, 0)
const totalQ = good.reduce((n,x)=>n+x.specs.reduce((m,s)=>m+(Number(s.target_q)||0),0), 0)
const empty = results.filter(x => !x || !x.specs || !x.specs.length).map(x=>x&&x.slug)
log(`done: ${good.length}/${SUBSTRANDS.length} sub-strands returned specs; ${totalTopics} topics, ~${totalQ} est questions. empty: ${empty.join(',')||'none'}`)

return { subject:'cooking', substrands:results, totals:{ substrands_ok:good.length, topics:totalTopics, est_questions:totalQ, empty } }
