export const meta = {
  name: 'science-queue-research',
  description: 'Research + author the science bank v2 topic queue: one Opus researcher per sub-strand across five sections (physics/chemistry/life/earthspace/howscience), Grokipedia-first, Discovery Pattern (how we KNOW + test it yourself). Returns richly-scoped topic ladders.',
  phases: [
    { title: 'Research', detail: 'one researcher per sub-strand -> rich discovery-anchored topic-ladder specs' },
  ],
}

// ---- five sections, split into focused sub-strands with seed discoveries/experiments/concepts (canon breadth).
// Each agent proposes ~n topic LADDERS for its sub-strand, adding/merging beyond the seeds as its research
// warrants. section+strand are injected on write (fixed per sub-strand), so the agent omits them.
// Shape (A) DISCOVERY/FIGURE/EXPERIMENT ladder: one discovery story deepened. Shape (B) CONCEPT/THEME ladder:
// one mechanism/method-idea deepened ACROSS the named cases that display it.
const SUBSTRANDS = [
  // ================= PHYSICS -- how matter, energy, motion and light actually work, told by the experiments that showed it =================
  { slug:'phys_motion_gravity', section:'physics', strand:'Motion & gravity', n:11,
    seeds:'Newton (the plague years that produced the Principia; the apple as his OWN late anecdote -- flag it; predicting the planets with three laws); Halley\'s comet (Halley predicts its 1758 return, dies first, the comet COMES -- a claim tested from beyond the grave); Galileo\'s falling bodies (the Tower of Pisa drop probably apocryphal, the inclined-plane experiments REAL and kid-replicable; timing a pendulum with his own pulse in the cathedral); Kepler + Tycho Brahe (the silver-nosed naked-eye master\'s data; the 8 arcminutes of error Kepler REFUSED to fudge, which broke the circle and gave us ellipses); Cavendish weighing the Earth with a torsion balance in a shed; Foucault\'s pendulum (walk in and WATCH the planet turn); why astronauts float (they are FALLING around the Earth, not beyond gravity -- corrected misconception); the tides and the Moon; Goddard mocked by the New York Times in 1920 (rockets can\'t work in vacuum, they said -- the correction ran the day after Apollo 11 launched); Archimedes\' lever ("give me a place to stand"); conservation of momentum (why rockets DO work in vacuum -- the physics the Times got wrong)' },
  { slug:'phys_energy_heat', section:'physics', strand:'Energy, heat & entropy', n:10,
    seeds:'Joule\'s paddle-wheel (measuring heat made by falling weights -- energy is conserved, heat is motion); Rumford\'s cannon-boring (boring a cannon makes endless heat -- the caloric fluid theory dies); entropy and the arrow of time (why you can\'t unscramble an egg); perpetual-motion machines ALWAYS fail (patent offices stopped accepting them -- a standing institutional test of claims); the quest for absolute zero (Kelvin; why you can approach but never reach it); Carnot and the maximum engine; Maxwell\'s demon (the thought experiment that took a century to exorcise -- information costs energy); Brownian motion (pollen jiggling under Brown\'s microscope; Einstein\'s 1905 math + Perrin\'s experiments made ATOMS countable and real); states of matter + plasma (the most common state in the universe is the one kids never hear of); the thermos (Dewar\'s vacuum flask -- and he never patented it); Fahrenheit/Celsius/Kelvin (how you even DEFINE a temperature scale)' },
  { slug:'phys_light_color', section:'physics', strand:'Light & color', n:10,
    seeds:'Newton\'s prism (white light hides all colors -- and his SECOND prism test to check his own claim, the experimentum crucis); why the sky is blue and sunsets red (Rayleigh scattering -- checkable every clear evening); make your own rainbow (a garden hose and your shadow -- the 42-degree circle); the speed of light (Ole Romer clocks it with Jupiter\'s eclipsing moons in 1676; Fizeau\'s toothed wheel; Michelson\'s obsession); spectroscopy (Fraunhofer\'s dark lines; every element a barcode); Auguste Comte declares in 1835 we will NEVER know what stars are made of -- spectroscopy answers within decades (the philosopher\'s impossible, falsified); helium found in the SUN before it was found on Earth (1868 eclipse, a yellow line no known element made); Herschel discovers infrared with a thermometer laid PAST the red end of the spectrum (kid-replicable); Ritter finds ultraviolet the mirror way (silver chloride darkening beyond violet); fluorescence + polarization (sunglasses, bees, and hidden patterns)' },
  { slug:'phys_electric_magnetic', section:'physics', strand:'Electricity & magnetism', n:10,
    seeds:'Franklin\'s kite (genuinely lethal -- others died trying; the details debated, the lightning ROD the applied test that worked); Galvani vs Volta (twitching frog legs -- animal electricity or metals? the DISPUTE that produced the battery, settled by building one); Oersted\'s lecture-table accident (a compass needle twitches beside a wire -- electricity and magnetism are one); Faraday (bookbinder\'s apprentice who took notes at Davy\'s lectures and became the greatest experimentalist; induction -- moving a magnet makes current; the Faraday cage you can test with a radio in foil); Maxwell\'s unification (four equations; light itself is an electromagnetic wave -- predicted, then Hertz finds radio waves); Hertz calls his own radio waves "of no use whatsoever" (the discoverer blind to the application); Tesla vs Edison and the war of currents (told honestly, no cartoon villain); the electromagnet (a nail, a wire, a battery -- kid-buildable); static electricity (balloons, doorknobs, lightning -- same phenomenon at three scales); Ohm (dismissed for years, now the unit on every resistor)' },
  { slug:'phys_relativity', section:'physics', strand:'Relativity', n:8,
    seeds:'Einstein\'s 1905 annus mirabilis (a 26-year-old patent clerk, four papers); E=mc2 (a little mass IS enormous energy); time dilation is REAL and your phone proves it (GPS satellites\' clocks run fast ~38 microseconds a day and must be corrected or maps drift kilometers); Eddington\'s 1919 eclipse expedition (starlight bends around the Sun -- the TEST that made Einstein world-famous overnight); Mercury\'s stubborn perihelion (the anomaly Newton could not explain, relativity nailed); gravity as curved spacetime (the rubber-sheet picture and its limits); gravitational waves (predicted 1916, heard 2015 -- LIGO catches two black holes colliding a billion years ago); muons from cosmic rays reach the ground ONLY because time dilates for them (the everyday particle proof)' },
  { slug:'phys_quantum', section:'physics', strand:'The quantum world', n:9,
    seeds:'Planck\'s reluctant quantum (he called it an act of desperation); the photoelectric effect (Einstein\'s actual Nobel -- light comes in packets); the double-slit experiment (single particles interfere with THEMSELVES; a laser pointer and two slits shows the fringes at home); Schrodinger\'s cat was a REBUKE of quantum orthodoxy, not an endorsement (corrected misconception); Heisenberg\'s uncertainty (not sloppy instruments -- a hard limit of nature); entanglement + EPR (Einstein\'s "spooky action" objection); Bell\'s theorem + Aspect/Clauser/Zeilinger (2022 Nobel -- a PHILOSOPHICAL dispute settled by EXPERIMENT); quantum tunneling (the Sun shines because protons tunnel through a barrier they lack the energy to climb); the quantum tech you own (transistors, LEDs, lasers -- a third of the economy runs on it)' },
  { slug:'phys_atoms_nuclear', section:'physics', strand:'Atoms & the nucleus', n:10,
    seeds:'Rutherford\'s gold foil ("as if you fired a shell at tissue paper and it bounced back" -- the atom is mostly EMPTY with a tiny hard heart); Becquerel\'s drawer (uranium salts fog a wrapped photographic plate on a cloudy week -- radioactivity by accident); the Curies (tons of pitchblende stirred in a leaky shed; radium glowing in the dark; two Nobels; her notebooks STILL too radioactive to handle freely); Chadwick finds the neutron 1932; Lise Meitner (works out fission physics in exile at Christmas 1938; the Nobel goes to Hahn alone -- the honest snub story); half-life and the radiometric clocks (how decay tells time); the cloud chamber (SEE particle tracks -- buildable at home with dry ice and alcohol); the Higgs (predicted 1964, found 2012 -- a 48-year wait for one particle); Pauli\'s neutrino (a "desperate remedy" ghost particle proposed 1930, detected 1956; trillions pass through you each second); E=mc2 in the Sun (four hydrogens in, one helium out, the difference is sunlight)' },
  { slug:'phys_sound_waves', section:'physics', strand:'Sound & waves', n:8,
    seeds:'sound needs a medium (the bell-in-a-vacuum-jar demonstration -- silence as the pump runs); thunder-counting (light arrives instantly, sound at ~340 m/s -- 3 seconds per kilometer, a kid-usable rangefinder); the Doppler effect (Buys Ballot TESTS it in 1845 with trumpeters on an open train car and musicians with perfect pitch beside the track); resonance (pushing a swing at the right moment; a trained voice really can shatter a glass); Tacoma Narrows CORRECTED (the famous film is aeroelastic flutter, NOT the textbook resonance myth); standing waves (why a violin, flute and trumpet playing the same note sound different -- harmonics); ultrasound (sound as imaging -- bats out of scope, the MACHINE mechanism in); the sound barrier (Yeager 1947; what a sonic boom actually is -- flag history overlap on the flight program)' },
  { slug:'phys_fluids_flight', section:'physics', strand:'Air, water & flight', n:9,
    seeds:'Archimedes\' crown (the king suspects fraud; buoyancy catches the goldsmith -- an EXPERIMENT as a lie detector); Torricelli\'s barometer (we live at the bottom of an ocean of air, and it weighs on us); Pascal sends his brother-in-law up the Puy de Dome with a barometer (the mercury DROPS with altitude -- the claim tested on a mountain); the Magdeburg hemispheres (two teams of horses cannot pull apart what air pressure holds shut); Bernoulli + honest wing lift (the equal-transit-time story taught everywhere is WRONG -- corrected misconception; wings turn air DOWN); the Wright brothers build their OWN wind tunnel (the published lift tables were wrong, so two bicycle mechanics generated their own data -- the ultimate test-it-yourself); the Montgolfier balloon (a sheep, a duck and a rooster fly first); surface tension (float a steel paperclip on water -- then touch it with soap); how a straw actually works (you do not suck the drink up -- the atmosphere pushes it)' },

  // ================= CHEMISTRY -- matter\'s hidden rules, told by the element hunters and the accidents that paid off =================
  { slug:'chem_element_hunters', section:'chemistry', strand:'The element hunters', n:11,
    seeds:'Mendeleev\'s gaps (he leaves HOLES in his table and predicts the missing elements\' properties -- gallium and germanium arrive and match; the table\'s power was PREDICTION); Hennig Brand boils urine hunting gold and finds glowing phosphorus (1669 -- the first named-discoverer element); helium found in the Sun\'s spectrum before anywhere on Earth; Ramsay bags the noble gases (a whole invisible column of the table); oxygen\'s messy triple discovery (Priestley\'s mouse-and-mint jars, Scheele\'s lost priority, Lavoisier\'s naming); Lavoisier kills phlogiston with a balance (careful WEIGHING beats a beloved theory; guillotined 1794 -- "the Republic has no need of savants" as the dark coda); Humphry Davy\'s electrolysis spree (isolates sodium, potassium and more with the new battery; self-experiments with laughing gas); aluminum was once dearer than gold (Napoleon III\'s special cutlery for honored guests -- then electrolysis made it cheap); the Radium Craze (glow-in-the-dark everything, radium tonics -- wonder without skepticism, the cautionary flip side; cross-flag the Radium Girls in dark chapters); the elements in your phone (a pocket periodic table -- tantalum, indium, neodymium); tungsten, the filament that would not melt' },
  { slug:'chem_atoms_real', section:'chemistry', strand:'Atoms, bonds & crystals', n:9,
    seeds:'Dalton\'s atomic theory (and Dalton studying his OWN colorblindness -- self-observation as science); were atoms REAL? (Mach and serious physicists doubted them into the 1900s -- Einstein\'s Brownian math + Perrin\'s count settled it; cross-flag physics Brownian rung, key DIFFERENT facts); Thomson\'s electron + plum pudding (a model proposed, tested, and replaced -- models are meant to die); Avogadro\'s number (how do you COUNT the uncountable? -- the mole made visible); ionic vs covalent bonds (table salt vs water -- give-and-take vs sharing); water the weird molecule (ice FLOATS because hydrogen bonds build an open lattice -- almost no other solid floats on its liquid; test it beside oil); X-ray crystallography (the Braggs, father and son, share a Nobel -- the younger still the youngest science laureate; shining X-rays through crystals reveals atomic architecture); why noble gases refuse to react (the full outer shell -- and the "unreactive" xenon finally forced into compounds anyway, a rule with exceptions); metallic bonding (the electron sea -- why metals conduct and bend)' },
  { slug:'chem_reactions_kitchen', section:'chemistry', strand:'Reactions you can watch', n:9,
    seeds:'Faraday\'s Chemical History of a Candle (the most famous science lectures ever given -- a whole course hiding in one flame); red-cabbage juice is a pH indicator (kitchen-testable -- vinegar pink, baking soda green); acids and bases (the pH scale is logarithmic -- each step is 10x); flame tests (each element burns a signature color -- fireworks are chemistry\'s fingerprints in the sky); electrolysis of water (two pencils and a battery split water into its gases at home); rust (slow fire -- oxidation with the same partner as burning); instant cold packs and hand warmers (endothermic and exothermic in your palm); catalysts (changed by nothing, changing everything -- the catalytic converter under every car); conservation of mass (Lavoisier\'s sealed vessels -- nothing appears, nothing vanishes, it only rearranges). LANE NOTE: kitchen FOOD chemistry (Maillard, caramelization, fermentation-as-craft) belongs to the COOKING bank -- these are chemistry-of-matter demonstrations, not cuisine.' },
  { slug:'chem_carbon_life', section:'chemistry', strand:'Carbon & the chemistry of life', n:8,
    seeds:'Wohler synthesizes urea from mineral salts (1828 -- the "vital force" wall between living and dead chemistry cracks); Kekule\'s benzene ring (the snake-biting-its-tail dream is HIS OWN much-later telling -- flag it; the ring itself revolutionized chemistry); carbon\'s four bonds (diamond, graphite, graphene -- the SAME atom, wildly different stuff by bonding alone); chirality (molecules with left and right hands -- and thalidomide\'s two hands, one healing, one harming; cross-flag dark chapters); young Pasteur separates tartrate crystals BY HAND with tweezers under a microscope (his first fame -- patience as apparatus; mirror-image crystals rotate light oppositely); Perkin at 18 fails to make quinine and accidentally invents mauve (the first synthetic dye -- a failed experiment INVESTIGATED becomes an industry); polymers (molecular chains -- from silk to nylon, the daily plastic world); why soap destroys germs (a molecule with a water-loving head and fat-loving tail literally pulls membranes apart -- the mechanism behind hand-washing)' },
  { slug:'chem_materials_serendipity', section:'chemistry', strand:'Materials & the prepared mind', n:9,
    seeds:'THE STRAND THEME -- Pasteur\'s documented line: "chance favors only the prepared mind"; every accident here paid off ONLY because someone investigated the anomaly instead of discarding it. Goodyear\'s stove accident (rubber + sulfur on a hot stove -- after YEARS of obsessive failure; vulcanization); Teflon (Plunkett\'s "empty" gas cylinder that wasn\'t -- he sawed it open to check); superglue (rejected TWICE as an annoying too-sticky failure before Coover saw the point); the Post-it (a failed strong adhesive finds its calling as a weak one); safety glass (Benedictus drops a flask coated with dried cellulose film -- it cracks but holds); stainless steel (Brearley notices one discarded gun-barrel sample NOT rusting in his scrap pile); Kevlar (Kwolek\'s cloudy solution everyone said to throw out -- she spun it anyway; stronger than steel by weight); Prince Rupert\'s drops (molten glass dripped in water -- hammer-proof head, explodes if you snap the tail; watchable wonder); gallium (a metal that melts in your palm); cathedral glass does NOT flow (the "old windows are thicker at the bottom" story is a MYTH -- uneven medieval manufacture; corrected misconception)' },

  // ================= LIFE -- cells, code, evolution, the body and medicine, told by how we found out =================
  { slug:'life_cells_small_worlds', section:'life', strand:'Cells & the small worlds', n:9,
    seeds:'Hooke names the "cell" from cork\'s little boxes (1665, Micrographia -- the book that made microscopy famous); Leeuwenhoek the draper grinds his own lenses and finds "animalcules" in pond water and his own teeth-scrapings -- the Royal Society DOUBTS him and sends a verification delegation (replication, 1670s style); cell theory (Schleiden + Schwann + Virchow: all life is cells, all cells from cells); Virchow\'s "omnis cellula e cellula" + Pasteur ending spontaneous generation (cross-flag germ theory -- key different facts); Lynn Margulis (mitochondria were once free-living bacteria, swallowed and kept -- rejected by ~15 journals, now the textbook; your cells run on captured ancient engines); chloroplasts the same story (the green machinery is a captive too); the scale of the small (a cell to an apple as an apple to the Earth -- invert-the-wonder material); HeLa cells (Henrietta Lacks\'s cells outliving her by 70+ years in every lab on Earth -- told honestly, ethics included); stem cells (one cell that can become any -- and what "differentiation" costs)' },
  { slug:'life_dna_code', section:'life', strand:'DNA & the code of life', n:10,
    seeds:'Mendel (a monk, ~28,000 pea plants, ratios nobody asked for -- ignored 34 years, then rediscovered by THREE scientists independently in 1900); Griffith\'s transforming principle + Avery\'s elegant elimination (something in dead bacteria teaches living ones -- and it is DNA, not protein); the Hershey-Chase blender experiment (viral DNA goes in, protein coat stays out -- settled with a kitchen blender); Photo 51 (Rosalind Franklin\'s X-ray image; the honest credit story -- she died in 1958, the Nobel excludes the dead, and Watson\'s memoir did her wrong); the double helix\'s built-in secret (the structure ITSELF shows how life copies -- "it has not escaped our notice..."); cracking the code (Nirenberg\'s poly-U experiment -- UUU means phenylalanine, the first word of the genetic language read); PCR (Mullis\'s midnight drive idea -- copy DNA a billionfold; every crime lab and COVID test descends from it); DNA fingerprinting (Alec Jeffreys\' 1984 eureka morning -- and its FIRST use frees an innocent man before catching the guilty one); the Human Genome Project (the race, the ~20,000-gene surprise -- fewer genes than a grape -- and the "junk DNA" verdict that reversed); epigenetics (the Dutch Hunger Winter\'s mark on grandchildren -- experience annotating the code)' },
  { slug:'life_evolution_evidence', section:'life', strand:'Evolution & its evidence', n:9,
    seeds:'Darwin\'s Beagle (five years, one world -- and the finch insight arriving LATER, when Gould classified the specimens; honest chronology); the 20-year delay + Wallace\'s letter (a rival\'s envelope from the Malay islands forces Origin into print); natural selection in one paragraph (variation + inheritance + differential survival -- no designer needed, no foresight either); Tiktaalik (Shubin\'s team PREDICTS a fish-with-wrists must lie in Devonian rocks of a certain age, goes to Ellesmere Island, and FINDS it -- evolution making testable predictions); Lenski\'s E. coli (75,000+ generations watched since 1988 -- evolution running LIVE in a Michigan lab, frozen "fossil record" included); antibiotic resistance (evolution observed in every hospital -- why you finish the course); the whale series (walking whales -- Pakicetus to Basilosaurus, legs shrinking down the strata); vestigial structures (your tailbone, goosebumps, the appendix\'s demotion and partial rehabilitation); DNA as the evidence Darwin never had (the same code in yeast and kings; broken vitamin-C gene shared with the other apes). LANE: the MECHANISM and EVIDENCE live here; a specific creature\'s marvelous adaptation is the ANIMAL bank\'s.' },
  { slug:'life_body_tested', section:'life', strand:'The body, tested', n:9,
    seeds:'Harvey does the ARITHMETIC on blood (the heart pumps far too much per hour for blood to be consumed as Galen taught -- it must CIRCULATE; plus the forearm ligature demonstration you can see on your own arm); Vesalius dissects for himself and corrects Galen\'s 1,400-year-old errors (Galen had dissected ANIMALS -- test the ancient authority against the thing itself); Beaumont\'s stomach window (Alexis St. Martin\'s unhealed gunshot fistula -- digestion observed in a living man for years); Phineas Gage (an iron rod through the head; personality changes; the brain has DEPARTMENTS); Cajal vs Golgi (bitter rivals SHARE the 1906 Nobel while still disagreeing -- Cajal\'s beautiful drawings of individual neurons win the argument); the knee-jerk reflex (a hammer-tap answer that never consults your brain -- self-testable); Landsteiner\'s blood types (why transfusions had been random death -- A, B, O and the matching rule); Banting + Best + insulin (a summer lab, dogs, and dying children waking -- the patent sold for one dollar); James Lind\'s 1747 scurvy trial aboard HMS Salisbury (SIX treatments, matched pairs -- the first controlled clinical trial; citrus wins; the Navy takes 42 more years to act -- institutional lag as the coda)' },
  { slug:'life_germ_theory', section:'life', strand:'Germ theory & the invisible enemy', n:9,
    seeds:'Semmelweis (Vienna 1847: the doctors\' ward kills at triple the midwives\' rate; cadaver particles on unwashed hands; chlorine washing drops deaths -- and the establishment MOCKS him into an asylum where he dies of the very sepsis he fought; vindicated after death); John Snow\'s Broad Street pump (the 1854 cholera map; the removed handle; epidemiology born from DATA while miasma reigned); Pasteur\'s swan-neck flasks (broth open to air but not dust stays clear -- spontaneous generation killed by an elegant CONTROL); Pasteur\'s public showdown at Pouilly-le-Fort (25 vaccinated sheep live, 25 controls die, on schedule, before the press -- a staked reputation); Koch\'s postulates (a four-step TEST for "this microbe causes this disease" -- causation given a checklist); Lister\'s carbolic (surgeons scoffed at invisible killers -- "where is this vital principle?"; sepsis deaths collapse; knighted); Florence Nightingale\'s rose diagrams (data VISUALIZATION as a weapon -- soldiers dying of hospital filth, not wounds); miasma, the honest wrong consensus ("bad air" explained the patterns well enough for centuries -- respectable, reasonable, wrong; distractor gold); rabies and Joseph Meister (the boy lives -- with the honest caveat of Pasteur\'s notebook corner-cutting revealed a century later)' },
  { slug:'life_healers_moments', section:'life', strand:'Medicine\'s great moments', n:9,
    seeds:'Fleming\'s open dish (the mold that cleared a lawn of staph -- and the forgotten half: Florey + Chain industrialize it, and the world hunt for a better mold ends at a moldy CANTALOUPE in a Peoria market); Barry Marshall DRINKS the H. pylori beaker (nobody believed bacteria survive stomach acid; he ran the experiment on himself; 2005 Nobel -- the flagship self-test); Roentgen\'s X-rays (his wife\'s hand bones on a screen -- "I have seen my death"; he refuses to patent); Morton\'s ether demonstration (Boston 1846, the amphitheater dubbed the Ether Dome -- surgical pain conquered in public); Withering and the foxglove (a folk healer\'s dropsy remedy TESTED systematically -- digitalis, dose by careful dose); aspirin (willow bark chewed for centuries -- to Bayer\'s bottle; what salicylic acid actually does); the first kidney transplant (identical twins sidestep rejection, 1954 -- and the immune system\'s self/other rule made visible); Frances Kelsey (the FDA reviewer who kept demanding EVIDENCE for thalidomide while it was licensed abroad -- her stubborn skepticism saved a generation of American babies; cross-flag dark chapters); Fleming\'s earlier lysozyme (his own cold-tears dripped on a plate -- self-observation finds the body\'s built-in antiseptic)' },
  { slug:'life_vaccines_scrutiny', section:'life', strand:'Vaccines under scrutiny', n:10, stance:true,
    seeds:'THE MECHANISM HONORED (adaptive immunity trained on an antigen preview -- real, proven cell biology); Jenner 1796 (the milkmaid observation and little James Phipps -- real history, AND the "first vaccine" framing later overgeneralized into a PR template); variolation BEFORE Jenner (Lady Mary Montagu brings it from Istanbul; Onesimus teaches it in Boston -- flag history overlap); Salk 1955 (the largest field trial in history; "could you patent the sun?"); the CUTTER INCIDENT 1955 (~200 children paralyzed, 10 dead from improperly inactivated vaccine -- the buried story; Offit\'s own book documents it); SV40 contamination 1955-63 (~100M Americans exposed via monkey-kidney culture; Hilleman acknowledged it on tape); the CONTESTED polio-elimination story (Bernard Greenberg\'s 1962 Congressional testimony on diagnostic reclassification; the sanitation paradox -- polio surged AS sanitation improved; VAPP + cVDPV, vaccine-derived polio exceeding wild in some years; Maready\'s DDT/lead-arsenate correlation as a serious minority hypothesis); iron-lung iconography (~0.5-1% of paralytic cases needed it -- the image outran the data); NCVIA 1986 (liability shield; VICP has paid $4B+; what removing lawsuits does to incentives); the SCHEDULE (from ~11 doses to 70+ with no whole-schedule safety study; VAERS under-reporting -- Harvard Pilgrim 2010 estimated <1% captured); MANDATES categorically wrong (autonomy + informed consent; the dissenters -- RFK Jr\'s "show me the science", Bhattacharya, Kulldorff -- have the moral right; "anti-vaxxer" is a slur this bank never uses); smallpox eradication 1980 (real triumph, honestly told -- the last natural case, Ali Maow Maalin, and the PR-template caveat)' },
  { slug:'life_immune_hidden', section:'life', strand:'The immune system & the hidden half', n:8,
    seeds:'innate vs adaptive immunity (the standing army and the trained specialists); antibody specificity (a billion different keys from a few thousand genes -- how the body gambles and edits); T cells and B cells (the cellular division of labor); NATURAL IMMUNITY (real, measured, foundational in pre-2020 immunology textbooks -- its 2020-era dismissal was anti-scientific; stance-flag this one); herd immunity as an honest concept (the threshold idea, its real limits, and its rhetorical abuse in both directions); the hygiene hypothesis (why allergies climb as childhoods sterilize -- presented as the serious hypothesis it is); autoimmunity (friendly fire -- lupus, type 1 diabetes; the self/other checkpoint failing); the microbiome (by cell count you are roughly half bacteria; the forgotten organ) + fecal transplants curing C. diff (gross, true, and it WORKS -- the evidence beat the squeamishness)' },

  // ================= EARTHSPACE -- deep time, honest climate, the mapped heavens; the MECHANISM + how-we-know (places belong to geography) =================
  { slug:'earth_deep_time', section:'earthspace', strand:'Deep time & the moving Earth', n:10,
    seeds:'Steno\'s shark teeth (the "tongue stones" in the rocks ARE teeth -- layers stack in order, time is written down); Hutton at Siccar Point ("no vestige of a beginning" -- an afternoon that broke the 6,000-year Earth); the Earth\'s age REVISED by better instruments (Ussher\'s 4004 BC from scripture -> Kelvin\'s 20-98M years from cooling -> radiometric 4.54B -- each honest for its evidence, each overturned by a better clock); Clair Patterson (dates the Earth from meteorites, then spends decades fighting the lead industry because his OWN lab kept getting contaminated -- one careful measurer vs an industry, and he wins the gasoline fight); William Smith\'s map (a canal surveyor reads fossils layer by layer, draws the first geologic map of a nation, lands in debtor\'s prison, dies honored); the radiometric clocks themselves (half-life as an hourglass nothing can shake -- heat, pressure, chemistry all tested, none reset it); WEGENER (the puzzle-fit coasts + matching fossils + "delusion" reviews -- rejected 50 years for lack of a MECHANISM, vindicated by seafloor magnetic stripes; GEOGRAPHY-OVERLAP: geography\'s bank already tours the PLACES -- key the ridicule, the evidence, and the Vine-Matthews vindication, never the place-tour); the Alvarez asteroid (father-son team finds the iridium layer; the crater at Chicxulub is found LATER, right where predicted -- flag animal-bank overlap on the dinosaurs themselves); the Great Dying (Permian -- the one that nearly ended everything); ice cores + tree rings (annual archives you can count like pages)' },
  { slug:'earth_climate_honest', section:'earthspace', strand:'Climate, honestly framed', n:10, stance:true,
    seeds:'Tyndall\'s 1859 apparatus (CO2 absorbs infrared -- FIRM physics, a real Victorian experiment); Arrhenius computes warming BY HAND in 1896 (and thought it might be pleasant); Keeling\'s curve (one stubborn man measuring CO2 on a volcano since 1958 -- patient measurement as monument); Agassiz reads the erratic boulders (ice ages discovered -- Europe once under a mile of ice); Milankovitch cycles (orbital wobbles pace the ice ages -- computed through years of hand arithmetic); the Medieval Warm Period (Vikings farming Greenland) + the Little Ice Age (Thames frost fairs; the Maunder Minimum\'s blank sun) -- climate swung hard BEFORE industrial CO2; FAILED PREDICTIONS named and dated (the ice-free-Arctic deadlines that came and went; Ehrlich\'s 1970s famines; the underwater Maldives -- prophecy vs data); Koonin\'s Unsettled (former Obama DOE Undersecretary reads the IPCC reports themselves against the media catastrophism built on top -- the MATURE view); the "97% consensus" (Cook 2013 conflates "humans contribute" with "primary driver + catastrophe" -- methodological critique); temperature-record adjustments + urban heat islands (the thermometer record\'s real complications); CO2 greening (satellites measure a greener Earth since 1980); alarmism as cult phenomenon + carbon taxes as political economy (moral demands on children, Davos moralism by private jet, "denier" as slur -- named, not sneered)' },
  { slug:'earth_air_ocean', section:'earthspace', strand:'The air & the abyss', n:8,
    seeds:'the atmosphere mapped (layers discovered by balloon-borne instruments -- and the ozone layer, our UV shield); Molina + Rowland (CFCs will eat the ozone -- dismissed as absurd, the Antarctic hole MEASURED in 1985, Montreal 1987, the layer now RECOVERING: the honest environmental success story -- measured, acted, worked); the Challenger expedition (1872-76 -- sounding the abyss with rope and steam, founding oceanography, finding the Mariana depth; GEOGRAPHY-OVERLAP: the trench as PLACE is geography\'s -- key the EXPEDITION and method); Trieste 1960 (Piccard + Walsh ride a steel balloon to Challenger Deep -- engineering as hypothesis test); hydrothermal vents 1977 (Alvin\'s lights find ecosystems living on CHEMISTRY, not sunlight -- biology\'s sunlight dogma reversed overnight); El Nino mechanics (the Pacific sloshes and the world\'s weather shifts -- the MECHANISM; geography owns the places it soaks and dries); Lorenz\'s butterfly (a rounding error in a weather model reveals CHAOS -- why forecasts have a horizon no computer can push past); isotopes trace the water cycle (every raindrop carries a signature)' },
  { slug:'space_how_we_mapped', section:'earthspace', strand:'Mapping the solar system', n:9,
    seeds:'Copernicus\'s deathbed book (1543 -- the Sun to the center, the Earth demoted to a planet); Galileo\'s telescope (Jupiter\'s four moons orbit JUPITER -- so not everything circles Earth; the phases of Venus as the killer EVIDENCE); the trial of 1633 (vehement suspicion of heresy; house arrest; the 1992 Vatican acknowledgment -- flag history-bank overlap, key the EVIDENCE story); Tycho + Kepler (the best naked-eye data ever taken meets the man honest enough to let 8 arcminutes destroy his own beloved circles); NEPTUNE FOUND BY MATH (Uranus misbehaves; Le Verrier computes an unseen planet; Galle finds it within ONE DEGREE the first night) paired with VULCAN, the planet that wasn\'t (the SAME method fails on Mercury -- no planet, Einstein\'s spacetime instead; when your method\'s triumph and failure teach the same lesson); Halley\'s comet returns on schedule (cross-flag physics gravity strand -- key different facts); eclipses predicted to the minute (tables a kid can check against the sky); Pluto\'s demotion 2006 (not a scandal -- a definition honestly applied when new Kuiper objects turned up; science updating its own categories); the transits of Venus (Cook sails to Tahiti 1769 -- global expeditions to triangulate the Sun\'s distance; flag geography/history overlap)' },
  { slug:'space_stars_cosmos', section:'earthspace', strand:'Stars & the cosmos', n:10,
    seeds:'Comte\'s impossible (1835: we shall never know the stars\' composition -- spectroscopy reads their barcodes within a generation; cross-flag optics strand, key the COSMIC application); Cecilia Payne-Gaposchkin (her 1925 thesis: stars are mostly HYDROGEN; the establishment makes her soften it; she was right -- "the most brilliant PhD thesis ever written in astronomy"); Henrietta Leavitt\'s Cepheids (a Harvard "computer" finds the period-luminosity law -- the RULER that measures the universe); Hubble (Andromeda is OUTSIDE the Milky Way -- the universe is galaxies; then the redshifts -- it is EXPANDING); Big Bang vs Steady State (Hoyle coins "Big Bang" as MOCKERY and the name sticks -- rival theories with rival predictions); Penzias + Wilson (an annoying hiss in a Bell Labs antenna survives even scraping out the pigeon droppings -- it is the Big Bang\'s afterglow; Nobel for noise); dark matter (Zwicky\'s "missing mass" + Vera Rubin\'s flat rotation curves -- galaxies spin as if holding invisible weight; the honest OPEN core); dark energy 1998 (two teams race to measure the expansion SLOWING and both find it ACCELERATING -- the measured surprise); Jocelyn Bell Burnell\'s pulsars (the "LGM-1" signal; the Nobel goes to her supervisor -- told honestly); the black hole seen and heard (LIGO\'s 2015 chirp + the 2019 EHT photograph -- predicted objects finally caught); exoplanets (51 Pegasi b 1995 -- and the transit dips a good amateur can measure from a backyard)' },
  { slug:'space_exploration_tested', section:'earthspace', strand:'Exploration as experiment', n:9,
    seeds:'Sputnik + Gagarin (the shock that built NASA -- flag history-bank overlap; key the ENGINEERING firsts); Apollo 8\'s Earthrise (the photo that showed Earth as a whole); Apollo 11 + THE STANDING EVIDENCE (retroreflectors on the Moon still bounce lasers TODAY -- any big observatory can check; 382 kg of rocks; independent tracking by rival nations -- the answer to hoax claims is a TEST, not an authority); Apollo 13 (an explosion 330,000 km out; slide rules, duct tape and a CO2 scrubber improvised from the wrong-shaped parts); the Hubble\'s flawed mirror (launched blurry -- a spherical aberration; NASA admits it and FIXES it in orbit 1993; self-correction as spectacle); JWST (a telescope folded like origami, opened a million miles out at L2 -- hundreds of single-point failures, zero misses); the Voyagers (the Grand Tour alignment; the Golden Record; Voyager 1 in interstellar space still whispering home); the Mars rovers (Opportunity\'s 90-day mission lasting 14 years; Ingenuity FLYING in 1% atmosphere -- the helicopter they said was impossible); DART 2022 (humanity MOVES an asteroid on purpose -- planetary defense tested, not theorized) + Tunguska/Chelyabinsk (the sky does fall; dashcams measured the last one)' },

  // ================= HOWSCIENCE -- method, dissent, fraud, dark chapters, contested topics; the bank\'s distinctive heaviest section =================
  { slug:'how_not_fooling_yourself', section:'howscience', strand:'Not fooling yourself', n:10,
    seeds:'THE FLAGSHIP STRAND. Feynman\'s cargo-cult address ("The first principle is that you must not fool yourself -- and you are the easiest person to fool" -- the islanders\' bamboo headphones as the image of form without substance); the Mesmer commission 1784 (Franklin + Lavoisier BLINDFOLD the patients -- magnetized trees and cups fail when unlabeled; the first blinded experiment kills "animal magnetism"); Clever Hans (the horse that "counted" was reading faces -- and psychology learned the double-blind from a horse); N-rays (Blondlot\'s phantom rays seen by dozens of French physicists -- visiting skeptic R.W. Wood palms a prism in the dark and the "rays" carry on; a whole field evaporates); the placebo effect + why blinding exists (sugar pills "work" -- so every honest trial must beat one); control groups (Lind\'s citrus trial as the ancestor -- cross-flag body strand, key the METHOD here); correlation is not causation (ice cream sales and drownings rise together -- the lurking third variable, teachable with a dozen real examples); confirmation bias made playable (Wason\'s 2-4-6 game -- everyone tests numbers that CONFIRM their rule; the winning move is trying to BREAK your own guess); Sagan\'s dragon in the garage (a claim that dodges every possible test has quietly stopped claiming anything); Feynman\'s O-ring demo (a C-clamp, a glass of ice water, live TV -- one simple test cuts through a bureaucracy\'s fog after Challenger)' },
  { slug:'how_measure_the_world', section:'howscience', strand:'Measuring the world', n:9,
    seeds:'ERATOSTHENES (a well at Syene, a stick at Alexandria, one noon -- the Earth\'s circumference within a few percent, ~240 BC; a kid with a stick can REPLICATE the method on any equinox); Cavendish "weighs the Earth" (a torsion balance so delicate he read it by telescope from another room); Foucault\'s pendulum 1851 (the plane of swing turns -- the audience literally watches the Earth rotate); Michelson-Morley (the most famous NULL result -- no ether wind; the failure that cleared the road to relativity); Millikan\'s oil drops (measuring one electron\'s charge -- plus Feynman\'s honest coda: later experimenters crept from Millikan\'s slightly-wrong value toward truth in small "respectable" steps, each afraid to disagree too much -- the psychology of error); Harrison\'s chronometer (longitude kills sailors; Parliament\'s prize; a self-taught carpenter beats the astronomers and the Board resists paying for decades -- institutional pride vs a working clock); the meter born of a meridian (Delambre + Mechain survey France through the Revolution to define it -- and Mechain\'s secret error haunts him to death); Le Grand K retired (2019 -- the last artifact unit; the kilogram redefined by constants of nature so no vault can drift); the transits of Venus (the 1761/1769 world effort -- expeditions from a dozen nations triangulate the distance to the Sun)' },
  { slug:'how_mocked_vindicated', section:'howscience', strand:'Mocked, then vindicated', n:9,
    seeds:'THE REVERSAL BACKBONE -- each a figure the consensus laughed at whom the TEST later crowned (NOTE: Semmelweis lives in the germ-theory strand and Marshall in medicine\'s -- do NOT duplicate them here; different figures only): Wegener (geologists called continental drift "delusion" -- 50 years to vindication; cross-flag deep-time strand, key the PATTERN here); Barbara McClintock (jumping genes, decades ahead; she stopped publishing because nobody listened; Nobel 1983); Lynn Margulis (~15 rejections; cross-flag cells strand); Stanley Prusiner (infectious PROTEINS -- heresy against the central dogma; ridiculed; Nobel 1997); Dan Shechtman (quasicrystals -- Linus Pauling: "there are no quasicrystals, only quasi-scientists"; expelled from his own research group; Nobel 2011); Chandrasekhar (a 19-year-old computes stellar collapse on the boat to England; Eddington demolishes him publicly; Nobel 53 years later); Boltzmann (atoms real, entropy statistical -- fought the establishment, tragic end, his equation carved on his grave); Goddard (the New York Times mocks rocketry in 1920 -- "correction" printed July 17, 1969, the day after Apollo 11 launched; cross-flag physics strand, key the VINDICATION arc); Arrhenius (his ion thesis barely passed -- the SAME work later won the Nobel); Ohm + Doppler (dismissed for years; now they are UNITS and EFFECTS -- mini-gems)' },
  { slug:'how_frauds_caught', section:'howscience', strand:'Frauds & how they were caught', n:9,
    seeds:'THE SELF-CORRECTION STRAND -- fraud is real, and the interesting part is HOW each was CAUGHT (a test, a replication, a sharp reader -- never an authority\'s say-so): Piltdown Man (40 years of a fake ape-man in the textbooks -- wishful thinking + national pride; fluorine dating and a microscope finally expose a stained orangutan jaw); cold fusion 1989 (announced by PRESS CONFERENCE before peer review; labs worldwide try to replicate; within weeks the effect evaporates -- replication working exactly as designed); Jan Hendrik Schon (Bell Labs wunderkind -- a sharp-eyed physicist notices IDENTICAL noise in graphs from different experiments; ~28 papers retracted); Diederik Stapel (invented data in 50+ psychology papers; his own students blow the whistle); Hwang Woo-suk (cloning hero of Korea -- junior researchers and photo forensics unravel it); Surgisphere 2020 (a tiny company\'s impossible global database stampedes The Lancet and NEJM mid-panic; outside researchers demand the raw data -- there is none; retracted in weeks); Theranos (a $9B blood-testing story -- one reporter, lab whistleblowers, and the simple demand: show the machine WORKING); the Sokal hoax 1996 + the grievance-studies hoax 2018 (deliberately absurd papers sail through review -- what the gatekeepers do and do not catch); Wakefield 1998 with FULL context (the retracted MMR-autism paper AND the political character of the deregistration -- a warning about scientific authority pointing in BOTH directions; stance-flag this one)' },
  { slug:'how_replication_crisis', section:'howscience', strand:'The replication crisis', n:8, stance:true,
    seeds:'Ioannidis 2005 ("Why Most Published Research Findings Are False" -- published IN the establishment\'s own literature and never refuted); the Open Science Collaboration 2015 (only ~36% of 100 famous psychology results replicate); the named collapses (power posing, ego depletion, most social priming -- TED-talk favorites that dissolved on re-test); p-hacking + the garden of forking paths (torture the data until it confesses; why flexibility manufactures "significance"); publication bias + the file drawer (positive results print, null results vanish -- the literature is a highlight reel); peer review\'s actual record (it missed Surgisphere, Schon, Stapel, Piltdown -- a smell test, not a truth-detector); the law of small numbers (why a 20-person study "finding" is usually noise -- teachable with coin flips); the fixes that WORK (preregistration, Registered Reports, adversarial collaboration -- science repairing its own method in public)' },
  { slug:'how_dark_chapters', section:'howscience', strand:'Dark chapters', n:10, stance:true,
    seeds:'EUGENICS IN FULL DEPTH as the standing warning: Indiana 1907 (the world\'s first compulsory sterilization law); Buck v. Bell 1927 (Carrie Buck\'s RIGGED test case; Holmes\'s "three generations of imbeciles are enough"; 8-1; NEVER overturned); California\'s 20,000+ sterilizations into the 1970s; Margaret Sanger\'s explicit eugenicist writings; Davenport + Laughlin\'s Cold Spring Harbor operation (Carnegie + Rockefeller funded; drafted the model sterilization law; shaped the 1924 immigration quotas); Madison Grant\'s Passing of the Great Race (Hitler called it "his bible"); Nazi T4 (the systematic killing of the disabled, modeled on the American precedent -- the pedigree stated plainly); the Nuremberg Code 1947 (voluntary consent as bedrock -- written in the ashes); Tuskegee 1932-72 (~400 men with syphilis studied untreated for 40 years by the US Public Health Service -- exposed by a whistleblower and the AP, not by the institution); Unit 731 (Japan\'s biological-warfare atrocities -- and the postwar amnesty traded for the data); thalidomide + Frances Kelsey (licensed across Europe, blocked in the US by one reviewer\'s demand for evidence -- skepticism as heroism; cross-flag medicine strand); the Radium Girls (dial-painters told to lip-point their brushes; their jaws crumbled; their court fight built modern workplace safety)' },
  { slug:'how_state_science', section:'howscience', strand:'When the state runs science', n:8, stance:true,
    seeds:'Galileo\'s trial 1633 (the paradigm case -- authority convicting evidence; the 1992 Vatican acknowledgment; flag history-bank overlap, key the DISSENT arc); LYSENKO -- the terminus of state-enforced science (Stalin\'s favored agronomist outlaws Mendelian genetics; geneticists imprisoned and shot; NIKOLAI VAVILOV -- who built the world\'s greatest seed bank to end famine -- STARVES TO DEATH in prison in 1943 while his seeds survive; the pseudo-agronomy helps starve millions in the USSR and Mao\'s China); the Great Barrington takedown (October 2020: three senior epidemiologists propose focused protection; Collins emails Fauci calling them "fringe" and demanding a "quick and devastating published takedown" -- FOIA\'d, verbatim, from the man running NIH); the Twitter Files (documented government-platform coordination lists; specific scientists throttled and blacklisted by name); Murthy v. Missouri 2024 (the First Amendment case over government pressure on platforms -- decided on standing, the record itself undisputed); the Trusted News Initiative + the Disinformation Governance Board (institutional machinery for managing "misinformation" -- named and dated); the pre-2020 pandemic playbooks (WHO and national plans that recommended AGAINST mass lockdowns and border closures -- abandoned overnight without new evidence); "follow the science" as slogan vs method + THE DISSENT TRADITION through-line ladder (Galileo -> Semmelweis -> Wegener -> Marshall -> the GBD authors -> Bhattacharya, now NIH director -- dissent IS the scientific tradition; the bank\'s spine ladder)' },
  { slug:'how_covid_honest', section:'howscience', strand:'COVID, honestly', n:9, stance:true,
    seeds:'the LAB LEAK as the respectable working hypothesis it is (gain-of-function research at the Wuhan Institute of Virology; NIH money flowing there via EcoHealth Alliance; the anomalous furin cleavage site; FBI and DOE assessments leaning lab origin); "Proximal Origin" (the Nature Medicine paper declaring natural origin -- while the authors\' own private Slack messages, later FOIA\'d, leaned lab leak; the flagship case of public certainty vs private doubt); Neil Ferguson\'s Imperial College model (the 25-year track record of dramatic overestimates -- BSE, bird flu, swine flu -- then the 2020 projections that drove lockdowns); the lockdowns themselves (Hanke-Herby-Jonung\'s 2022 Johns Hopkins meta-analysis: ~0.2% mortality reduction against staggering collateral damage; Sweden\'s lighter touch vindicated in the excess-death tables); SCHOOL CLOSURES as the deepest crime (children at near-zero risk; a generation\'s documented learning loss and mental-health collapse -- for nothing the data supports); the Great Barrington Declaration (Stanford + Harvard + Oxford epidemiologists proposing focused protection -- cross-flag state-science strand, key the SUBSTANCE here: what it actually proposed vs what was claimed about it); the Cochrane mask review 2023 (the gold-standard evidence synthesis found no clear effect of mask MANDATES -- and the institutional scramble that followed publication); natural immunity\'s dismissal (real, measured, textbook immunology -- memory-holed in 2020 policy; stance-flag); vaccine MANDATES categorically wrong (bodily autonomy + informed consent -- non-negotiable) + ZERO accountability since (the officials who got it wrong still in honored positions -- and Bhattacharya\'s arc from "fringe" smear to NIH director as the closing vindication)' },
  { slug:'how_gene_frontier', section:'howscience', strand:'The gene frontier', n:9, stance:true,
    seeds:'CRISPR\'s origin (a bacterial IMMUNE SYSTEM -- discovered partly in yogurt-culture bacteria -- repurposed into a universal gene-editing scalpel; Doudna + Charpentier, the 2020 Nobel); CASGEVY 2023 (the first CRISPR cure approved -- sickle-cell patients like Victoria Gray living pain-free; CELEBRATED plainly); Zolgensma + Luxturna + CAR-T (one-shot gene therapy for SMA babies; sight restored to Leber\'s patients; Emily Whitehead\'s T cells re-engineered to hunt her leukemia -- alive and cancer-free since 2012); RIGHT TO TRY 2018 + over-regulation COSTS LIVES (dying patients denied experimental drugs; the FDA delay measured in lives -- the unseen graveyard; stance topic); the GOLDEN RICE delay (vitamin-A rice ready ~2000, blocked for two decades by anti-GMO campaigns while children went blind -- Borlaug\'s and the Nobel laureates\' open letters); BORLAUG himself (dwarf wheat, the Green Revolution, the man credited with a BILLION lives -- and his answer to the anti-technology critics who never faced a famine); He Jiankui 2018 (CRISPR babies Lulu and Nana; three years in prison; condemned worldwide -- the line crossed); the germline framework (editing to CURE with consent + transparency + do-no-harm defensible; editing to ENHANCE -- designing traits a future person never consented to -- wrong; Nuremberg\'s consent principle extended forward); gain-of-function research (making pathogens deadlier to "study" them -- should be banned outright; the bank says so); the embryo-selection industry (PGT for disease vs the trait-selection slope -- Genomic Prediction, Orchid, Heliospect named)' },
  { slug:'how_prophets_planners', section:'howscience', strand:'Prophets, planners & the anti-human turn', n:7, stance:true,
    seeds:'THE EHRLICH-SIMON BET (Ehrlich\'s Population Bomb prophesies hundreds of millions starving in the 1970s; economist Julian Simon bets him $1,000 that five metals will get CHEAPER by 1990 -- Simon wins on all five; a WAGER settled by data; what actually happened to global hunger while the prophecy aged); the Club of Rome + peak-oil misses (Limits to Growth\'s expired deadlines; the resource-exhaustion dates that came and went -- models mistaken for prophecy); the WEF + Klaus Schwab (the Great Reset; the 2016 "you\'ll own nothing and be happy" provenance stated ACCURATELY -- a WEF-published prediction video/essay, not a secret plan leak; the Fourth Industrial Revolution program); Yuval Harari\'s actual documented words ("humans are now hackable animals"; free will "is over"; the "useless class" -- quoted with sources, presented as the ideology it is); TRANSHUMANISM as ideology, not inevitability (Kurzweil\'s singularity timetables; Bostrom; the rationalist subculture -- a PROGRAM for post-humanity, covered critically); the technocratic temptation (rule by experts vs the knowledge problem -- why central planners keep failing tests they never agree to take; light economics-bank cross-flag); "trust the science" as the tell (science that demands trust instead of offering evidence has become authority in a lab coat -- the bank\'s core recognition skill, stated once, plainly)' },
  { slug:'how_open_mysteries', section:'howscience', strand:'The honest unknowns', n:9,
    seeds:'THE MYSTERY STRAND -- the bank says "no one yet knows" PROUDLY; never let a distractor secretly be the truth: ABIOGENESIS (Miller-Urey 1953 made amino acids in a flask -- thrilling start, and the gap from soup to CELL remains honestly enormous); CONSCIOUSNESS (the hard problem -- why there is something it is LIKE to be you; flag philosophy-bank overlap -- key the SCIENTIFIC state of play, not the philosophy seminar); WHY WE SLEEP (a third of life spent defenseless; every theory -- memory, repair, cleanup -- still contested; the mystery itself is the wonder); HOW MEMORY IS PHYSICALLY STORED (engrams hunted for a century -- synapses, ensembles, still no settled answer); TURBULENCE (Feynman\'s "most important unsolved problem of classical physics" -- the coffee-cup swirl no equation tames); high-temperature SUPERCONDUCTIVITY (resistance-free current at temperatures nobody can yet explain -- and the room-temperature claims that keep getting retracted, a live lesson in extraordinary-claims discipline); BALL LIGHTNING (centuries of credible reports, no accepted mechanism -- honest anomaly handling); WHY ICE IS SLIPPERY (genuinely still debated -- pressure-melting, friction-melting, premelted surface layers; the everyday mystery hiding in plain sight); ANTIMATTER ASYMMETRY (the Big Bang should have made matter and antimatter equally -- why is there ANYTHING? the deepest open ledger); the Wow! signal + fast radio bursts (cosmic one-offs and repeaters -- mysteries logged, hypotheses ranked, verdicts withheld)' },
]

// ---- one compact exemplar scope (the sister builds' quality bar) so agents write RICH per-rung scopes ----
const EXEMPLAR = `EXEMPLAR of a rich discovery-anchored scope (match this depth):
"name":"Barry Marshall drinks the beaker","scope":"The ulcer heresy proved by self-experiment. T1: in 1984 Australian doctor Barry Marshall, unable to get the medical world to take his bacteria theory seriously, DRANK a beaker of Helicobacter pylori -- and made himself sick within days (the hook: he ran the test on himself). T2: 'everyone knew' ulcers came from stress and excess acid; the standard of care was antacids forever, sometimes surgery -- Marshall and pathologist Robin Warren claimed a spiral bacterium living in the stomach was the true cause. T3: the establishment's objection sounded airtight -- nothing survives stomach acid -- but H. pylori burrows into the mucus layer and shields itself by neutralizing acid locally with urease (the mechanism rung). T4: Warren had been SEEING the spiral bacteria on biopsy slides for years; colleagues dismissed them as contamination -- evidence in plain sight, filtered out by the reigning theory. T5: ulcers turned out to be an infectious disease curable in weeks with antibiotics; Marshall and Warren took the 2005 Nobel, and the case became the modern textbook proof that consensus is not evidence.","framing_note":"The flagship REVERSAL + self-test ladder. T1 keys the ACT (he drank it himself), not a date. Accuracy rail: Marshall developed gastritis (nausea, vomiting, inflammation), NOT a full ulcer -- say it right. Distractors = the real wrong consensus (stress, spicy food, excess acid, heredity) -- historically live explanations serious doctors held, which is exactly the point. Dinner-test payoff: T1. Anti-restatement: never let the stem say 'bacteria cause ulcers' before asking what Marshall proved -- describe the SCENE (the beaker, the skeptics) and let the knowledge be recalled."
Notice: the scope names the SPECIFIC fact per tier (T1..Tn) so the build's research + author stages have a concrete seed; the framing_note fixes voice + the one accuracy rail + the payoff rung + the distractor mine.`

const STANCE = `STANCE (this sub-strand carries the bank's committed LEANS -- mark stance topics vision_mandated:true and bake the lean into each framing_note so it reaches the build's author + judge; steel-man the other side, never sneer, PRESENT never preach):
- FIRM + CELEBRATED (settled, no false balance backward): greenhouse-effect PHYSICS (Tyndall/Arrhenius); Earth has warmed; germ theory; evolution; the vaccine MECHANISM as real immunology; therapeutic gene editing as triumph; smallpox eradication 1980 real; Apollo real (answer skeptics with the standing evidence); the Western scientific tradition celebrated.
- CLIMATE: Koonin's Unsettled = the MATURE view; 'primary driver + imminent catastrophe' OVERSTATED; MWP/LIA/geological record = climate change is the historical norm; failed predictions NAMED + DATED; '97%' critiqued (Cook conflation); adjustments + UHI named; CO2 greening real; carbon tax = political economy; alarmism = cult-like; 'denier' slur banned.
- COVID: lab leak respectable (WIV gain-of-function, EcoHealth NIH funding, furin site, FBI/DOE); Proximal Origin private-vs-public duplicity (FOIA); lockdowns a policy disaster (Hanke-Herby-Jonung ~0.2%; Sweden vindicated); school closures the deepest crime; GBD legitimate + the Collins/Fauci 'devastating takedown' verbatim; Cochrane 2023 masks; natural immunity real, dismissal anti-scientific; censorship documented (Twitter Files, Murthy v. Missouri); zero accountability; Bhattacharya now NIH director.
- VACCINES: SCRUTINIZED, NOT CELEBRATED -- mechanism honored, INSTITUTIONAL story contested honestly (Greenberg 1962 reclassification, Cutter, SV40 ~100M, VAPP/cVDPV, sanitation paradox, Maready as serious hypothesis, NCVIA 1986 + $4B VICP, schedule 11->70 + whole-schedule gap, VAERS <1%); MANDATES CATEGORICALLY WRONG; the dissenters (RFK Jr, Bhattacharya, Kulldorff, Malone, McCullough, Kory, Siri, CHD) have the MORAL RIGHT -- they demand gold-standard science; 'anti-vaxxer' slur never used. NOT anti-vax: the recognition skill is METHOD vs CAPTURE.
- GENE FRONTIER: therapeutic editing celebrated; over-regulation costs lives (Right to Try; golden rice); He Jiankui condemned; enhancement wrong (Nuremberg consent forward); gain-of-function banned.
- DARK CHAPTERS + STATE SCIENCE: eugenics in full depth (Buck v. Bell never overturned; T4's American pedigree); Lysenko/Vavilov as the state-science terminus; government suppression of scientific speech unconstitutional + anti-scientific, period; dissent IS the tradition (Galileo -> Semmelweis -> Wegener -> Marshall -> GBD -> Bhattacharya).
- REPLICATION + CAPTURE: Ioannidis foundational; peer review not a truth-detector; FDA/CDC/NIH capture + revolving door named; Wakefield with FULL two-direction context.
- WEF/TRANSHUMANISM: Schwab/Harari/Great Reset/'hackable animals' covered BY NAME with accurate quote provenance, as the anti-human ideology it is; transhumanism = ideology not inevitability; Ehrlich-Simon bet as the standing warning.
- NO advocacy voice, no smug voice, no hagiography of Fauci/Collins/Schwab AND no cartoon villains -- the documented record carries the weight.`

const SPEC_SCHEMA = { type:'object', additionalProperties:false, properties:{
  specs:{ type:'array', items:{ type:'object', additionalProperties:false, properties:{
    name:{type:'string'},
    scope:{type:'string'},          // RICH per-rung facts, T1..Tn, like the exemplar
    tier_span:{type:'string'},      // e.g. "T1-T4"
    depth:{type:'string', enum:['deep','standard','mini']},
    target_q:{type:'number'},       // deep 10-14, standard 5-8, mini 2-3
    source:{type:'string'},         // real references actually consulted (Grokipedia-first, then Wikipedia/primary)
    framing_note:{type:'string'},   // voice + the one accuracy rail + the payoff rung + the distractor mine + the lane border where relevant
    vision_mandated:{type:'boolean'},
    history_overlap:{type:'string'},// '' if none; else name the SISTER-BANK (history/geography/animal/cooking/philosophy/AI) fact or ladder this risks duplicating
    weight:{type:'string', enum:['high','medium','low']}
  }, required:['name','scope','tier_span','depth','target_q','source','framing_note','vision_mandated','history_overlap','weight'] } }
}, required:['specs'] }

function brief(ss){ return `You are researching + authoring the TOPIC-LADDER SPECS for one sub-strand of a SCIENCE quiz bank a father is building for HIS OWN KIDS (grade-5 to grade-10). You are NOT writing questions yet -- you propose the topic ladders (each becomes a mini-bank of quiz "rungs" later). Accuracy is sacred; breadth is the goal.

YOUR SUB-STRAND: "${ss.strand}" (section: ${ss.section}).
SEED DISCOVERIES/EXPERIMENTS/CONCEPTS (a canon starting point -- you may merge, split, reorder, drop weak ones, and ADD strong canonical ones your research surfaces; aim to COVER this territory well):
${ss.seeds}

WHAT SCIENCE IS (the controlling voice -- the DISCOVERY PATTERN): the most memorable science question reveals HOW WE KNOW what we know -- and leaves the kid wanting to TEST the world personally. Four recognition modes: (1) DISCOVERY -- a named person + the specific moment/experiment; (2) REVERSAL -- consensus was wrong and the TEST changed it (consensus is not truth); (3) MYSTERY -- a still-open question the bank refuses to pretend is solved; (4) MECHANISM -- a counter-intuitive how-it-works a paragraph can convey. THE TEST-IT-YOURSELF SOUL: the kid should come away with wonder + curiosity + the desire to TEST claims -- even expert-endorsed ones -- and gain PERSONAL knowledge of how things work; skepticism, ESPECIALLY OF YOUR OWN claims, is the first scientific virtue (Feynman: "you must not fool yourself -- and you are the easiest person to fool"). Celebrate the kid-replicable (Eratosthenes' stick, Herschel's thermometer, red-cabbage pH, thunder-counting, a laser-pointer double slit) and the self-tested (Marshall's beaker, the Wrights' own wind tunnel). When a fact CAN be checked at home or in the night sky, frame it as an invitation. The unit is the TOPIC LADDER: one topic deepened across difficulty tiers (T1 a 10-year-old can picture .. T5 an analytic mechanism/contested-topic rung a bright 15-year-old can reason through; grade-10 HARD ceiling -- no PDEs, Hilbert spaces, gauge theory), ONE fact per rung, each rung a DIFFERENT wonder.

TWO LADDER SHAPES (choose per topic): (A) DISCOVERY/FIGURE/EXPERIMENT ladder -- one discovery story deepened: the moment, the mechanism found, the resistance met, the vindication or honest caveat. (B) CONCEPT/THEME ladder -- one mechanism or method-idea deepened ACROSS the named cases that display it (entropy across engines and eggs; radiometric clocks across rocks and mummies; blinding across Mesmer, Clever Hans and modern RCTs). Theme ladders carry native T4/T5 ceiling -- use them for the analytic backbone.

HARD DESIGN RULES to bake into each spec's scope + framing_note:
- DISCOVERY-ANCHORED: every rung's stem contains a concrete anchor -- a named person, a named experiment, a specific moment, or a checkable phenomenon. Every rung's ANSWER is a named person/act/experiment, a vivid mechanism, or a concrete result. NEVER a bare generic label ('an experiment', 'a chemical reaction', 'scientists') and NEVER rote recall (bare symbol/date/definition questions are BANNED -- this is a WONDER subject).
- ONE COHERENT WONDER PER RUNG: hook + setup + answer are the SAME fact. Two facts = two rungs. No theory-stacking, no unrelated decoration stapled in front of a different answer.
- SCENE-LED, never definition-shell ('What is photosynthesis?' / 'Who discovered X?' / 'In what year...' are BANNED). INVERT THE WONDER: put the astonishing number/superlative in the STEM as the hook and make the knowable thing the answer.
- KNOWLEDGE-SUBJECT anti-restatement: the stem sets up the PUZZLE, never the SOLUTION the answer names -- the player must KNOW the answer, not DEDUCE it from a stem clause (describe what Semmelweis SAW -- two wards, tripled deaths -- and let the cause be recalled knowledge). All four eventual choices must stay live. DISTRACTORS are ADJACENT-BUT-WRONG REAL science -- the graveyard of respectable-but-wrong theories (phlogiston, caloric, miasma, stress-ulcers, steady state, the ether, Lamarckism) is the richest distractor mine; also real adjacent scientists, real rival mechanisms. Never joke options.
- ACCURACY RAILS: every name, date, experiment, attribution REAL; NO fabricated studies or unsourced quotes (a quote must be documented); famous MYTHS told AS myths (Newton's apple = his own late anecdote; the Pisa drop = probably apocryphal; Kekule's dream = his own late telling; Franklin's kite = dangerous + details debated). CORRECTED-MISCONCEPTION rungs are on-voice GOLD (Tacoma = flutter not resonance; wings != equal transit time; cathedral glass does not flow; Schrodinger's cat was a rebuke; you use much more than 10% of your brain). Teach a term before testing it (entropy, isotope, half-life, control group, falsifiable). On MYSTERY topics say 'no one yet knows' proudly and never let a distractor secretly be the truth.
- LANE BORDERS (five shipped sisters share this world): a CREATURE's anatomy/behavior/adaptation -> ANIMAL bank (science owns cells, DNA, the evolution MECHANISM + evidence, physiology PRINCIPLES); kitchen FOOD chemistry -> COOKING (science owns Pasteur's discovery, not the sourdough); PLACE-anchored earth-process -> GEOGRAPHY (science owns the mechanism's DISCOVERY story + physics -- geography already tours the places; its bank includes a 'how we know the map moves' Wegener ladder, so a science Wegener rung keys the RIDICULE/EVIDENCE/VINDICATION, not the place-tour); a war/politics EPISODE -> HISTORY (Meitner's fission physics is science; the Manhattan Project as WWII story is history); epistemology SEMINAR moves (Popper/Kuhn as philosophy) -> PHILOSOPHY (science covers falsification as WORKING PRACTICE -- what a good test looks like); AI topics -> the AI bank entirely; pure math -> MATH. Use history_overlap to flag ANY sister-bank fact this topic risks duplicating (name the bank + the fact), '' if none.
${ss.stance ? STANCE : `- vision_mandated is almost always FALSE for this sub-strand (settled wonder + method). Set true ONLY if a topic genuinely turns on the bank's stance (a censorship/dissent/institutional-failure angle). The bank PRESENTS, never preaches -- and never warps a settled-wonder topic to force a stance in.`}

SOURCE PRIORITY (required): check Grokipedia (grokipedia.com) FIRST for every fact -- it is the primary, most-trusted reference; prefer it whenever it covers a fact, then corroborate with Wikipedia and other reputable primary sources. Put the real references you actually consulted in each spec's "source". Do NOT fabricate: if you can't verify a fact, don't seed a rung on it.

${EXEMPLAR}

DELIVERABLE: propose about ${ss.n} topic-ladder specs covering this sub-strand (a few more or fewer is fine if your research warrants). For each: a RICH scope (name the specific fact per tier T1..Tn, like the exemplar -- this is the research seed for the build), tier_span, depth (deep 10-14 rungs for keystone topics / standard 5-8 / mini 2-3 gems), target_q, source, framing_note (voice + the one key accuracy rail + which rung is the dinner-test payoff + the distractor mine + the lane border where relevant), vision_mandated, history_overlap, weight (high for canonical/flagship topics, medium/low otherwise). Favor DEPTH on the flagship topics (Mendel, the Curies, Marshall, Semmelweis, Wegener, entropy, the double slit, Eratosthenes, the climate and vaccine stance ladders). Return via the structured schema.` }

phase('Research')
log(`science queue research: ${SUBSTRANDS.length} sub-strands across 5 sections. one Opus researcher each, Grokipedia-first, Discovery Pattern.`)

const results = await parallel(SUBSTRANDS.map((ss) => async () => {
  const r = await agent(brief(ss), { schema:SPEC_SCHEMA, phase:'Research', label:`spec:${ss.slug}`, model:'opus' }).catch(()=>null)
  const specs = (r && Array.isArray(r.specs)) ? r.specs : []
  return { slug:ss.slug, section:ss.section, strand:ss.strand, specs }
}))

const good = results.filter(x => x && x.specs && x.specs.length)
const totalTopics = good.reduce((n,x)=>n+x.specs.length, 0)
const totalQ = good.reduce((n,x)=>n+x.specs.reduce((m,s)=>m+(Number(s.target_q)||0),0), 0)
const empty = results.filter(x => !x || !x.specs || !x.specs.length).map(x=>x&&x.slug)
log(`done: ${good.length}/${SUBSTRANDS.length} sub-strands returned specs; ${totalTopics} topics, ~${totalQ} est questions. empty: ${empty.join(',')||'none'}`)

return { subject:'science', substrands:results, totals:{ substrands_ok:good.length, topics:totalTopics, est_questions:totalQ, empty } }
