"""Player-facing text for quirks and powers.

Two tables, both keyed by quirk id:

  QUIRK_HINT  shown in the tracking menu while a quirk is still LOCKED.
              In-character, tied to the figure the quirk is named for.
              It points at the kind of thing to do without naming the
              number or the exact condition -- the discovery is the fun.

  QUIRK_DESC  shown once a quirk is UNLOCKED (tracking menu and the
              unlock popup). Says in plain words what the reward does,
              then a line of flavor.

The short reward line (`_QUIRK_EFFECTS`), the exact trigger
(`_QUIRK_TRIGGER`) and the unlock quote (`_QUIRK_FLAVOR`) stay in
quirk_system.py. tests/test_quirk_text.py asserts every quirk has an
entry in both tables and that no hint quotes its own threshold.
"""

# What each stat does, appended to rewards that raise it.
_STR = "Strength raises how much you can carry."
_CON = "Constitution raises your maximum HP and SP."
_DEX = "Dexterity improves your armor class."
_INT = "Intelligence raises your maximum MP."
_WIS = "Wisdom adds a second to your quiz timer for every point."
_PER = "Perception widens how far you can see."


QUIRK_HINT = {
    'mithridates':   "The old king took a little poison every day. What bites you may yet feed you.",
    'tiresias':      "The prophet lost his eyes and found his sight. Truth does not need light.",
    'odin':          "Nine nights on the windy tree, and all he did was wait.",
    'scheherazade':  "She read aloud what no one had yet named, night after night, and lived.",
    'paracelsus':    "The physician learned his art by being ill. Sickness teaches, and takes its fee.",
    'siegfried':     "He bathed in what the dragon bled. Taste what your enemies carry in them.",
    'musashi':       "The master needs only one cut. End your fights with the plainest of strikes.",
    'rasputin':      "They poisoned him, shot him and drowned him. Stand at death's door, and walk away again.",
    'merlin':        "A wizard's apprentice waves every stick he finds, long before he knows what it does.",
    'buddha':        "The storm rages and the sage sits. Stillness in the presence of danger is a discipline.",
    'hephaestus':    "The smith fits the same piece again and again, until it sits like skin.",
    'cassandra':     "Everyone told her she was wrong, and she kept speaking. Error, endured, becomes its own wisdom.",
    'sisyphus':      "The boulder rolls back. The lid stays shut. He walks to the next one anyway.",
    'job':           "Every snare the pit could set was set for him, and he did not curse.",
    'orpheus':       "He walked among the dead and raised no hand. Stand close to danger, and do not strike.",
    'tantalus':      "The feast was always spoiled before it reached his lips. Even ruin fills a stubborn belly.",
    'asclepius':     "The healer's staff is wound with a serpent. Learn the venomous ones from the inside.",
    'fisher_king':   "The wounded king prayed from his sickbed. Ask when you are nearly broken.",
    'anansi':        "The spider's mind is a tangle, and still he finds the right thread.",
    'prometheus':    "Each day the wound was opened, and each day he bore it. Bleed long, and often.",
    'penelope':      "By day she wove, and by night she unpicked it. On and off, on and off.",
    'dionysus':      "The god of the vine drinks deepest when the world is already swimming.",
    'apollo':        "The archer god does not miss, and does not stop at one perfect volley.",
    'athena':        "The owl has looked on every creature that walks the dark. Meet them all.",
    'loki':          "The trickster wears what others would throw away, and wears it gladly for a while.",
    'thor':          "The hammer was never traded for another. Keeping faith with one weapon is an oath.",
    'beowulf':       "He met the monster with empty hands, for honour's sake.",
    'norns':         "The three sisters return to the thread of what was, again and again.",
    'jormungandr':   "The serpent takes up its tail and lets it go, without end. One blade, taken up and set down.",
    'shiva':         "The destroyer sees truly only from inside the illusion. Stay there a long while.",
    'enkidu':        "The wild man knew every beast by its flesh. Take what the hunt gives, from every kind.",
    'perseus':       "He never looked at her directly. Turn the enemy's own power back upon it.",
    'theseus':       "The hero left no passage of the labyrinth unwalked.",
    'persephone':    "What goes down in winter returns in spring. Master the finest dishes, from many sources.",
    'hermes':        "The messenger is here, and then elsewhere. Distance is a habit worth breaking often.",
    'sibyl':         "The prophetess had answered a great deal while she was still young.",
    'valkyrie':      "The chooser of the slain strikes from far off.",
    'ahasverus':     "The wanderer is never allowed to rest. The road is very, very long.",
    'circe':         "Her cauldron held a different change for every guest. Cook for every kind of gift.",
    'gawain':        "The girdle was won by a knight who was already hurt. Win the fights you begin behind in.",
    'ariadne':       "The thread is for getting out. Do not linger where you land.",
    'morgan':        "The enchantress's power sharpens as her body fails.",
    'cuchulainn':    "Terror took the Hound of Ulster, and he killed anyway.",
    'fenrir':        "The wolf was bound and bound again, and grew in the binding. Endure your afflictions.",
    'kali':          "The dancer destroys the same demon as often as it rises.",
    'medusa':        "Those who stared turned to stone. Those who could not see her answered her.",
    'green_knight':  "He took the axe on his neck and laughed. Survive the blows that ought to end you.",
    'narcissus':     "He could not stop looking at what was his.",
    'cerberus':      "The hound keeps the threshold between above and below, and knows it better than anyone.",
    'ragnarok':      "At the end of the world, arrive barely breathing.",
    'spartacus':     "He fought in chains. Kill while something still binds you.",
    'ramanujan':     "He saw numbers the way others see faces. One life, and a great many sums.",
    'ibn_battuta':   "The traveller left no province unvisited. A handful will not do.",
    'tesla':         "The inventor never tired of making sparks fly.",
    'de_medici':     "Every vault has its price, and the banker has paid a great many.",
    'leonidas':      "The king fought wherever there was ground to stand on. Leave no field without a battle.",
    'confucius':     "The master taught best when heaven smiled on him. Think deeply while you are favoured.",
    'zoroaster':     "The prophet prayed at every threshold he crossed.",
    'boudicca':      "The queen was bloodied first, and repaid it many times over.",
    'solomon_q':     "The king asked for wisdom, not riches. Answer the deep questions, again and again.",
    'atalanta':      "No one outran her. Be gone before the dust has settled.",
    'galileo':       "He would not stop measuring the heavens. Practise the natural arts.",
    'caesar':        "He came, he saw, and a very great many fell before him.",
    'shakespeare':   "The playwright read and wrote more words than anyone alive.",
    'wanderlust_q':  "For some, the road is the only home there is.",
    'nostradamus':   "The seer read the past through a fog in his own head.",
    'archimedes':    "He knew how the world moves and what it costs. Two disciplines, one lever.",
    'machiavelli':   "The secretary prepared without rest. One life, and a great many right answers.",
    'darwin':        "What survives is what has suffered every kind of hardship.",
    'hypatia':       "She taught the numbers and the stars together.",
    'philosophers_stone': "The Great Work is the naming of every thing. Know what you carry, over and over.",
    'atlas_burden':  "The Titan never set the sky down. Carry very nearly all you can bear.",
    'zeus_bolt':     "Lightning is only speed made visible. Be quickened, many times.",
    'gorgon_ward':   "Feel your flesh turn toward stone, and live. More than once.",
    'phoenix_rising': "The bird must burn almost to nothing before it rises. Many times over.",
    'eye_storm':     "At the centre of the storm nothing touches you. Cross whole floors unscathed.",
    'iron_will':     "The body is frozen and the blows still fall. Bear them.",
    'battle_trance': "Somewhere past the hundredth kill, the warrior stops counting.",
    'second_sight':  "The blind seer consults what he remembers.",
    'iron_ration':   "An army marches on its stomach, and marches a very long way.",
    'shadow_step':   "Walk unseen until walking unseen is all you know.",
    'focused_scholar': "Mastery is patience, counted in right answers.",
    'arcane_surge':  "The art grows with use. Cast, and cast again.",
    'death_wish':    "Some only fight their best with one foot in the grave.",
    'wandering_star': "The planets were called wanderers because they never stay put.",
    'time_dilation': "An unbroken run of truth bends the hour itself.",
    'mirror_mind':   "A mind that has named a great many things is hard to deceive.",
    'metabolic':     "On the long walk, the body becomes a furnace.",
    'venom_lore':    "Two sicknesses at once teach more than either alone.",
    'war_cry':       "Fear is fuel, if you kill while it burns.",
    'mind_fortress': "A clouded mind that still answers truly is building walls.",
    'temporal_shield': "Take enough blows and you learn their rhythm.",
    'ancestral_q':   "Those who came before walked every corridor. So should you.",
    'mystic_eye':    "Arrive already hearing every mind on the floor, on floor after floor.",
    'life_drain':    "Kill when you are almost dead yourself, and something flows back.",
    'reality_anchor': "When you can trust neither your thoughts nor your eyes, hold on.",
    'runic_armor':   "Fire, frost and lightning, all warded in the same moment.",
    'astral_form':   "Spend long enough unseen and the body becomes optional.",
    'sage_counsel':  "The past rewards those who study it.",
    'ouroboros':     "The serpent that eats its own tail has no end. Neither does the list of answers.",
    'diogenes':      "He threw away his cup when he saw a child drink from cupped hands. Set down what you lean on, and go deeper without it.",
    'duck_of_doom':  "You should know better than to pick up a duck in a dungeon. If you do, be patient with it.",
    # --- added 2026-10-04 ---
    'eratosthenes':  "He measured the whole earth with a stick and a shadow. Know the lands well.",
    'aesop':         "The fabulist knew every beast's nature. Learn the animals, one answer at a time.",
    'apicius':       "The gourmand wrote down every dish he ever tasted. Know your kitchen.",
    'aquinas':       "The Dumb Ox answered every question put to him, one article at a time. Know the sacred stories.",
    'adam_smith':    "No one directs the market, and still it finds its way. Understand what things cost.",
    'johnson':       "The lexicographer defined every word himself. Know how language is built.",
    'hercules':      "Twelve labours, twelve named terrors, and not one of them ordinary.",
    'pythagoras':    "Three, four, five: the oldest harmony there is. Let your strikes climb the same steps.",
    'achilles':      "His mother held him by the heel, and it was never covered. Fight as he was made.",
    'daedalus':      "The craftsman never met a lock he could not open, and never fumbled one.",
}


QUIRK_DESC = {
    'mithridates':   "You can no longer be poisoned or diseased, for the rest of this run. You fed on what poisoned you until your blood stopped noticing.",
    'tiresias':      f"Perception +2. {_PER} You learned to answer without your eyes, and now you notice what the sighted miss.",
    'odin':          "Permanent telepathy: every monster on the floor is shown to you, through walls and darkness. Long waiting opened an eye that does not close.",
    'scheherazade':  f"Intelligence +1. {_INT} Reading what you could not yet name taught you to read anything.",
    'paracelsus':    "You resist draining and disease for the rest of this run: neither can sap your stats again. What made you ill has made you a physician.",
    'siegfried':     "Permanent magic resistance: confusion, charm, fear, silence and hallucination no longer take hold. The blood of your enemies has hardened your skin.",
    'musashi':       "An attack that ends on a chain of exactly 1 deals double damage. One cut, properly made, is enough.",
    'rasputin':      f"Constitution +2. {_CON} You have been nearly dead so often that your body has stopped taking it seriously.",
    'merlin':        f"Intelligence +1. {_INT} Every unknown wand you dared to wave left a little of its secret behind.",
    'buddha':        "Permanent displacement: monsters strike at where you seem to be, and miss about three times in ten. Stillness has made you hard to find.",
    'hephaestus':    "Armor for that slot needs one fewer correct answer to put on. You have fitted that piece so often your hands do it alone.",
    'cassandra':     f"Wisdom +1. {_WIS} You were wrong many times and kept going; that is where judgement comes from.",
    'sisyphus':      f"Wisdom +1. {_WIS} The chests that beat you taught you more than the ones that opened.",
    'job':           "Permanent levitation: you float just above the floor, so floor traps cannot catch you. Having suffered every snare, you no longer touch the ground they are set in.",
    'orpheus':       "On every floor you enter, monsters begin slowed for 5 turns. You carry a quiet with you that the dungeon needs a moment to shake off.",
    'tantalus':      f"Strength +1. {_STR} You ate ruin until it made you stronger.",
    'asclepius':     f"Wisdom +1. {_WIS} You know the venomous creatures the way a healer does: from the inside.",
    'fisher_king':   "You may pray again in half the usual time. Heaven has grown used to hearing from you at your worst.",
    'anansi':        f"Intelligence +1. {_INT} A tangled head is no obstacle to a mind that enjoys the tangle.",
    'prometheus':    "Permanent regeneration: you recover 1 HP every turn. The wound opens; the wound closes. You have learned to outlast it.",
    'penelope':      f"Perception +1. {_PER} All that fastening and unfastening has given you an eye for small things.",
    'dionysus':      f"Wisdom +1. {_WIS} You drank through the visions and came out the other side seeing straighter.",
    'apollo':        f"Intelligence +1, and 3 more seconds on the math combat timer. {_INT} Perfect volleys have become your habit.",
    'athena':        f"Wisdom +1. {_WIS} You have looked on a host of creatures, and nothing in the dark is strange to you now.",
    'loki':          f"Wisdom +2. {_WIS} Wearing what was meant to harm you has taught you how harm is made.",
    'thor':          "The weapon you kept faith with gains +2 enchantment for good. It has drunk enough battle at your side to remember it.",
    'beowulf':       "Your bare-handed attacks deal bonus base damage that grows with depth. You proved you never needed the sword.",
    'norns':         "Recall Lore is ready again in half the usual time. The thread of the past comes to your hand more easily each time you reach for it.",
    'jormungandr':   "With that weapon, every attack that lands at all counts as one link longer than you earned. The serpent has its tail: the end of one strike is the start of the next.",
    'shiva':         f"Wisdom +1. {_WIS} You lived inside the illusion long enough to see how it is put together.",
    'enkidu':        f"Strength +1. {_STR} You have taken meat from a great many beasts and learned what each is made of.",
    'perseus':       "+2 to all saving throws: poison, paralysis, fear and the rest are easier to shrug off. You have practised turning the blow aside.",
    'theseus':       f"Perception +1. {_PER} You leave no corridor unwalked, and the habit has sharpened your eye.",
    'persephone':    "A ruined dish still gives you half its SP and HP. What goes down into the dark comes back, a little.",
    'hermes':        "Haste lasts twice as long on you. You have been in two places often enough that speed clings to you.",
    'sibyl':         "2 more seconds on the math combat timer. You answered a great deal while still near the surface, and the habit of quickness stayed.",
    'valkyrie':      f"Dexterity +1. {_DEX} You have chosen the slain from a distance, and your hands are surer for it.",
    'ahasverus':     "Permanent searching: hidden doors and traps beside you reveal themselves as you pass. No one has looked at more walls than you.",
    'circe':         f"Constitution +1. {_CON} You have cooked for every kind of change, and some of it has stayed with you.",
    'gawain':        f"Constitution +1. {_CON} You have won too many fights from behind to be easily finished now.",
    'ariadne':       f"Intelligence +1. {_INT} You find the way out before most people have found the way in.",
    'morgan':        f"Intelligence +2. {_INT} Your magic was sharpest when your body was failing, and it has kept the edge.",
    'cuchulainn':    f"Strength +2, and you can never be feared again. {_STR} The battle-frenzy is yours now: what frightens you only makes you kill faster.",
    'fenrir':        f"Constitution +1. {_CON} Every binding you outlasted left you a little harder to bind.",
    'kali':          f"Wisdom +1. {_WIS} You have destroyed the same creature so many times that you understand it completely.",
    'medusa':        f"Dexterity +2. {_DEX} Fighting without your eyes taught your body to move before your mind could ask.",
    'green_knight':  f"Constitution +1. {_CON} The blows that should have ended you have taught you how to take one.",
    'narcissus':     f"Perception +1. {_PER} You have studied your own belongings so closely that nothing about them escapes you.",
    'cerberus':      "Permanent warning: you sense monsters within 5 tiles, even through walls. You have guarded so many thresholds that nothing crosses one unnoticed.",
    'ragnarok':      f"Constitution +5. {_CON} You reached the end of the world with almost nothing left, and kept walking.",
    'spartacus':     f"Strength +1 and Constitution +1. {_STR} {_CON} You learned to fight in chains.",
    'ramanujan':     f"Intelligence +1, and 5 more seconds on the math combat timer. {_INT} The numbers have started answering before you finish asking.",
    'ibn_battuta':   f"Perception +1. {_PER} You have surveyed more of this place than anyone who ever entered it.",
    'tesla':         f"Intelligence +1. {_INT} So many sparks have passed through your hands that you understand the current itself.",
    'de_medici':     f"Wisdom +1. {_WIS} Every lock is a price, and you have learned to pay in knowledge.",
    'leonidas':      f"Constitution +2. {_CON} You have stood and fought on every kind of ground.",
    'confucius':     f"Wisdom +1. {_WIS} You did your deepest thinking under heaven's favour, and some of the favour remained.",
    'zoroaster':     f"Wisdom +1, and 1 more second on the math combat timer. {_WIS} You carried prayer onto floor after floor.",
    'boudicca':      f"Strength +2. {_STR} They drew first blood. You have been collecting on the debt ever since.",
    'solomon_q':     f"Wisdom +2. {_WIS} You asked the deep questions often enough that the answers began to stay.",
    'atalanta':      f"Dexterity +2. {_DEX} You are gone before the dust settles.",
    'galileo':       f"Intelligence +1. {_INT} You kept measuring the world until it gave up its patterns.",
    'caesar':        "Every stat +1. You came, you saw, and the number of the fallen is past easy counting.",
    'shakespeare':   f"Intelligence +1. {_INT} You have read so many scrolls that language has become your instrument.",
    'wanderlust_q':  "Walking drains your SP at half the usual rate. The road has become the place you rest.",
    'nostradamus':   f"Wisdom +2. {_WIS} You read the past clearly through a fog in your own head, and the clarity stayed when the fog lifted.",
    'archimedes':    f"Intelligence +1. {_INT} You know both how the world moves and what it costs, which is all a lever needs.",
    'machiavelli':   f"Wisdom +1, and 1 more second on the math combat timer. {_WIS} Relentless preparation has become your nature.",
    'darwin':        f"Constitution +2. {_CON} You have suffered nearly every affliction this place offers, and adapted to each.",
    'hypatia':       f"Intelligence +2. {_INT} You hold the numbers and the natural world in the same hand.",
    'philosophers_stone': "Power, 1 use this run. Blessed and Brilliant for 10 turns: all quiz timers run 25% longer, and INT and WIS each rise by 1. You have named so many things that for a moment you can see how all of them fit.",
    'atlas_burden':  "Power, 2 uses this run. Heroic for 20 turns: Strength +2 while it lasts. You have carried the sky; a little more is nothing.",
    'zeus_bolt':     "Power, 3 uses this run. Hasted and shock-proof for 15 turns: monsters act half as often and lightning cannot hurt you. You have been quickened so often that you can call it down yourself.",
    'gorgon_ward':   "Power, 2 uses this run. For 15 turns you cannot be put to sleep or paralysed, and monsters miss your true position about three times in ten. You have felt stone creeping in, and learned to refuse it.",
    'phoenix_rising': "Power, 1 use this run. Restores all your HP at once. You have been ash before, and you know the way back.",
    'eye_storm':     "Power, 3 uses this run. Invisible and Blessed for 10 turns: monsters miss you three times in ten and your quiz timers run 25% longer. The calm at the centre is yours to step into.",
    'iron_will':     "Power, 2 uses this run. Shielded and Reflecting for 10 turns: +2 armor class, physical damage halved, and monster status attacks may bounce back. They froze your body once; the will simply waited.",
    'battle_trance': "Power, 3 uses this run. Heroic for 15 turns: Strength +2 while it lasts. Past a certain number of kills, warrior and weapon stop being separate things.",
    'second_sight':  "Power, 3 uses this run. Telepathy and Clairvoyance for 15 turns: every monster on the floor is shown, and a wide area of the map around you is revealed. Blindness taught you another way of seeing.",
    'iron_ration':   "Power, 5 uses this run. Restores 100 SP at once. A soldier who knows his own feet can march on almost nothing.",
    'shadow_step':   "Power, 3 uses this run. Invisible and Phasing for 5 turns: monsters miss you three times in ten, and you can walk through walls. You have been the shadow so long the walls no longer object.",
    'focused_scholar': "Power, 2 uses this run. Brilliant for 10 turns: INT +1 and WIS +1, which also adds a second to your quiz timer. Mastery is knowing which question comes next.",
    'arcane_surge':  "Power, 2 uses this run. Restores all your MP and makes you Brilliant for 10 turns (INT +1, WIS +1). The art does not tire the soul that practises it; it feeds it.",
    'death_wish':    "Power, 3 uses this run. Heroic and Hasted for 10 turns: Strength +2, and monsters act half as often. You fight best at the edge, so you have learned to bring the edge with you.",
    'wandering_star': "Power, no limit, ready every 50 turns. Teleports you to a random spot on the floor. Even the stars do not stay fixed.",
    'time_dilation': "Power, 1 use this run. Stops time for 10 turns: no monster can act while you move freely. An unbroken run of right answers has taught you where the seams in the hour are.",
    'mirror_mind':   "Power, 2 uses this run. Reflecting and Magic Resist for 10 turns: monster status attacks may bounce back, and mind-affecting magic slides off. A mind that reflects does not absorb lies.",
    'metabolic':     "Power, 3 uses this run. Restores 100 SP at once. The body is a furnace, and you have learned to stoke it at will.",
    'venom_lore':    "Power, 3 uses this run. Cures poison and makes you immune to poison and disease for 20 turns. To name the poison is to begin its cure.",
    'war_cry':       "Power, 3 uses this run. Hasted for 8 turns: monsters act half as often. Fear screams through you now instead of at you.",
    'mind_fortress': "Power, 3 uses this run. Instantly clears confusion, blindness, hallucination, stun and fear. The walls you built inside cannot be breached from outside.",
    'temporal_shield': "Power, 2 uses this run. Shielded for 25 turns: +2 armor class and physical damage halved. Every blow you took taught your body the rhythm of the next.",
    'ancestral_q':   "Power, 2 uses this run. Clairvoyance for 20 turns: a wide area of the map around you is revealed. Those who walked these halls before you lend you what they saw.",
    'mystic_eye':    "Power, 3 uses this run. Telepathy, Clairvoyance and Warning for 15 turns: every monster shown, the map around you revealed, and nearby threats sensed through walls. To see everything is not paranoia. It is completion.",
    'life_drain':    "Power, 3 uses this run. Restores a quarter of your maximum HP. At the edge of death, taking life back has become a reflex.",
    'reality_anchor': "Power, 2 uses this run. Instantly clears every debuff on you. When the world bends, you have learned to be the point that does not.",
    'runic_armor':   "Power, 2 uses this run. For 10 turns you are immune to fire, cold and lightning, and fire and cold attacks are thrown back at their source. All weather, to one dressed in elder runes.",
    'astral_form':   "Power, 2 uses this run. Levitating, Invisible and Phasing for 8 turns: you float over traps, monsters miss you three times in ten, and walls do not stop you. The body is a guest; you have learned to step outside.",
    'sage_counsel':  "Power, 3 uses this run. Blessed for 15 turns: all quiz timers run 25% longer. History is what we learned from what happened, and you have learned a great deal.",
    'ouroboros':     "Power, 1 use this run. Hasted, Shielded and Regenerating for 20 turns: monsters act half as often, physical damage is halved, and you recover 1 HP a turn. The serpent swallows its tail and is never diminished.",
    'diogenes':      f"Wisdom +2. {_WIS} You set down the thing everyone said you needed, and found your own eyes were enough.",
    'duck_of_doom':  "A celestial duckling has hatched from the hat and follows you as a pet. Always trust a duck wearing a hat.",
    # --- added 2026-10-04 ---
    'eratosthenes':  f"Perception +1. {_PER} You know the shape of the world well enough to measure it from where you stand.",
    'aesop':         f"Wisdom +1. {_WIS} You know every beast's nature, and a little of your own.",
    'apicius':       f"Constitution +1. {_CON} A cook who knows the kitchen this well is never badly fed.",
    'aquinas':       f"Wisdom +1. {_WIS} You have answered the sacred questions one article at a time.",
    'adam_smith':    f"Wisdom +1. {_WIS} You can see the hand no one else can: what every thing costs, and why.",
    'johnson':       f"Intelligence +1. {_INT} You know how language is built, down to the joints.",
    'hercules':      f"Strength +2. {_STR} Twelve named terrors lie behind you. The labours are done.",
    'pythagoras':    f"Intelligence +1. {_INT} Three, four, five: your strikes climbed the oldest harmony there is.",
    'achilles':      f"Dexterity +1. {_DEX} You fought as he was made, with nothing on the heel, and learned to keep it out of reach.",
    'daedalus':      f"Dexterity +1. {_DEX} No lock has beaten you in a long while, and your fingers know it.",
}


def quirk_hint(qid: str) -> str:
    """Hint shown while the quirk is locked ('' if none)."""
    return QUIRK_HINT.get(qid, '')


def quirk_description(qid: str) -> str:
    """Explanation shown once the quirk is unlocked ('' if none)."""
    return QUIRK_DESC.get(qid, '')
